CREATE TABLE  AirportCode(ID INT IDENTITY  PRIMARY KEY, NAME VARCHAR(50),ThreeCode VARCHAR(5),FourCode VARCHAR(5),AirportName  VARCHAR(255),EnName  VARCHAR(100));


insert into AirportCode VALUES(null,'阿克苏','AKU','ZWAK','阿克苏机场','AKSU');
insert into AirportCode VALUES(null,'阿勒泰','AAT','ZWAT','阿勒泰机场','ALTAY');
insert into AirportCode VALUES(null,'安康','AKA','ZLAK','安康机场','ANKANG');
insert into AirportCode VALUES(null,'安庆','AQG','ZSAQ','安庆(天柱山）机场','ANQING');
insert into AirportCode VALUES(null,'鞍山','AOG','ZYAS','鞍山机场','ANSHAN');
insert into AirportCode VALUES(null,'保山','BSD','ZPBS','保山云瑞机场','BAOSHAN');
insert into AirportCode VALUES(null,'包头','BAV','ZBOW','包头二里半机场','BAOTOU');
insert into AirportCode VALUES(null,'昌都','BPX','ZUBD','西藏昌都邦达机场','CHAMDO');
insert into AirportCode VALUES(null,'北海','BHY','ZGBH','北海福城机场','BEIHAI');
insert into AirportCode VALUES(null,'北京','PEK','ZBAA','北京首都机场','BEIJING');
insert into AirportCode VALUES(null,'蚌埠','BFU','ZSBB','蚌埠机场','BENGBU');
insert into AirportCode VALUES(null,'长春','CGQ','ZYCC','长春龙嘉国际机场','CHANGCHUN');
insert into AirportCode VALUES(null,'常德','CGD','ZGCD','常德桃花源(斗姆湖)机场','CHANGDE');
insert into AirportCode VALUES(null,'长沙','CSX','ZGHA','长沙黄花机场','CHANGSHA');
insert into AirportCode VALUES(null,'长治','CIH','ZBCZ','长治王村机场','CHANGZHI');
insert into AirportCode VALUES(null,'常州','CZX','ZSCG','常州奔牛机场','CHANGZHOU');
insert into AirportCode VALUES(null,'朝阳','CHG','ZYCY','辽宁朝阳机场','CHAOYANG');
insert into AirportCode VALUES(null,'成都','CTU','ZUUU','成都双流机场','CHENGDU');
insert into AirportCode VALUES(null,'赤峰','CIF','ZBCF','赤峰玉龙机场','CHIFENG');
insert into AirportCode VALUES(null,'重庆','CKG','ZUCK','重庆江北机场','CHONGQING');
insert into AirportCode VALUES(null,'达州','DAX','ZUDX','达州(河市)机场','DAZHOU');
insert into AirportCode VALUES(null,'迪庆','DIG','ZPDQ','迪庆香格里拉机场','DIQING');
insert into AirportCode VALUES(null,'大连','DLC','ZYTL','大连国际机场','DALIAN');
insert into AirportCode VALUES(null,'大理','DLU','ZPDL','大理荒草坝机场','DALIXIAGUAN');
insert into AirportCode VALUES(null,'丹东','DDG','ZYDD','丹东浪头机场','DANDONG');
insert into AirportCode VALUES(null,'大同','DAT','ZBDT','大同云冈机场','DATONG');
insert into AirportCode VALUES(null,'张家界','DYG','ZGDY','张家界荷花机场','ZHANGJIAJIE');
insert into AirportCode VALUES(null,'敦煌','DNH','ZLDH','敦煌机场','DUNHUANG');
insert into AirportCode VALUES(null,'恩施','ENH','ZHES','恩施机场','ENSHI');
insert into AirportCode VALUES(null,'克拉科夫','KRK','EPKK','克拉科夫机场','KRAKOW');
insert into AirportCode VALUES(null,'富蕴','FYN','ZWFY','富蕴机场','FUYUN');
insert into AirportCode VALUES(null,'锦州','JNZ','ZYJZ','锦州小岭子机场','JINZHOU');
insert into AirportCode VALUES(null,'赣州','KOW','ZSGZ','赣州黄金机场','GANZHOU');
insert into AirportCode VALUES(null,'格尔木','GOQ','ZLGM','格尔木机场','GOLMUD');
insert into AirportCode VALUES(null,'广汉','GHN','ZUGH','广汉机场','GUANGHAN');
insert into AirportCode VALUES(null,'广州','CAN','ZGGG','广州白云机场','GUANGZHOU');
insert into AirportCode VALUES(null,'桂林','KWL','ZGKL','桂林两江机场','GUILIN');
insert into AirportCode VALUES(null,'贵阳','KWE','ZUGY','贵阳龙洞堡机场','GUIYANG');
insert into AirportCode VALUES(null,'哈尔滨','HRB','ZYHB','哈尔滨太平机场','HARBIN');
insert into AirportCode VALUES(null,'海口','HAK','ZJHK','海口美兰机场','HAIKOU');
insert into AirportCode VALUES(null,'海拉尔','HLD','ZBLA','内蒙古海拉尔东山机场','HAILAR');
insert into AirportCode VALUES(null,'哈密','HMI','ZWHM','哈密机场','HAMI');
insert into AirportCode VALUES(null,'杭州','HGH','ZSHC','杭州萧山机场','HANGZHOU');
insert into AirportCode VALUES(null,'汉中','HZG','ZLHZ','汉中西关机场','HANZHONG');
insert into AirportCode VALUES(null,'合肥','HFE','ZSOF','合肥骆岗机场','HEFEI');
insert into AirportCode VALUES(null,'黑河','HEK','ZYHE','黑河机场','HEIHE');
insert into AirportCode VALUES(null,'衡阳','HNY','ZGHY','衡阳东江机场','HENGYANG');
insert into AirportCode VALUES(null,'和田','HTN','ZWTN','和田机场','HETIAN');
insert into AirportCode VALUES(null,'香港','HKG','VHHH','香港赤?角国际机场','HONG KONG');
insert into AirportCode VALUES(null,'黄山','TXN','ZSTX','黄山屯溪机场','HUANGSHAN');
insert into AirportCode VALUES(null,'台州','HYN','ZSLQ','台州路桥（原黄岩路桥）机场','TAIZHOU');
insert into AirportCode VALUES(null,'呼和浩特','HET','ZBHH','呼和浩特白塔国际机场','HOHHOT');
insert into AirportCode VALUES(null,'佳木斯','JMU','ZYJM','佳木斯机场','JIAMUSI');
insert into AirportCode VALUES(null,'嘉峪关','JGN','ZLJQ','嘉峪关机场','JIAYUGUAN');
insert into AirportCode VALUES(null,'吉林','JIL','ZYJL','吉林二台子机场','JILIN');
insert into AirportCode VALUES(null,'济南','TNA','ZSJN','济南遥墙机场','JINAN');
insert into AirportCode VALUES(null,'济宁','JNG','ZSJG','济宁机场','JINING');
insert into AirportCode VALUES(null,'景德镇','JDZ','ZSJD','景德镇罗家机场','JINGDEZHEN');
insert into AirportCode VALUES(null,'西双版纳','JHG','ZPJH','景洪(西双版纳)机场','JINGHONG');
insert into AirportCode VALUES(null,'晋江','JJN','ZSQZ','泉州晋江机场','QUANZHOU');
insert into AirportCode VALUES(null,'福州','FOC','ZSFZ','福州长乐机场','FUZHOU');
insert into AirportCode VALUES(null,'酒泉','CHW','NNNN','酒泉机场','JIUQUAN');
insert into AirportCode VALUES(null,'九江','JIU','ZSJJ','九江庐山机场','JIUJIANG');
insert into AirportCode VALUES(null,'克拉玛依','KRY','ZWKM','克拉玛依机场','KARAMAY');
insert into AirportCode VALUES(null,'喀什','KHG','ZWSH','喀什机场','KASHGAR');
insert into AirportCode VALUES(null,'库尔勒','KRL','ZWKL','库尔勒机场','KORLA');
insert into AirportCode VALUES(null,'昆明','KMG','ZPPP','昆明长水机场','KUNMING');
insert into AirportCode VALUES(null,'库车','KCA','ZWKC','库车机场','KUQA');
insert into AirportCode VALUES(null,'兰州','LHW','ZLLL','兰州机场','LANZHOU');
insert into AirportCode VALUES(null,'临沧','LNJ','ZPLC','临沧机场','LINCANG');
insert into AirportCode VALUES(null,'拉萨','LXA','ZULS','拉萨贡嘎机场','LHASA');
insert into AirportCode VALUES(null,'连云港','LYG','ZSLG','连云港白塔埠机场','LIANYUNGANG');
insert into AirportCode VALUES(null,'丽江','LJG','ZPLJ','丽江三义机场','LIJIANG');
insert into AirportCode VALUES(null,'临沂','LYI','ZSLY','临沂沭埠岭机场','LINYI');
insert into AirportCode VALUES(null,'柳州','LZH','ZGZH','柳州白莲机场','LIUZHOU');
insert into AirportCode VALUES(null,'洛阳','LYA','ZHLY','洛阳机场','LUOYANG');
insert into AirportCode VALUES(null,'泸州','LZO','ZULZ','泸州蓝田机场','LUZHOU');
insert into AirportCode VALUES(null,'澳门','MFM','VMMC','澳门机场','MACAU');
insert into AirportCode VALUES(null,'芒市','LUM','ZPMS','芒市机场','MANGSHI');
insert into AirportCode VALUES(null,'梅县','MXZ','ZGMX','梅县机场','MEIXIAN');
insert into AirportCode VALUES(null,'牡丹江','MDG','ZYMD','牡丹江海浪机场','MUDANJIANG');
insert into AirportCode VALUES(null,'绵阳','MIG','ZUMY','绵阳南郊机场','MIANYANG');
insert into AirportCode VALUES(null,'南昌','KHN','ZSCN','南昌昌北机场','NANCHANG');
insert into AirportCode VALUES(null,'南充','NAO','ZUNC','南充高坪机场','NANCHONG');
insert into AirportCode VALUES(null,'南京','NKG','ZSNJ','南京禄口机场','NANJING');
insert into AirportCode VALUES(null,'南宁','NNG','ZGNN','南宁吴圩机场','NANNING');
insert into AirportCode VALUES(null,'南通','NTG','ZSNT','南通兴东机场','NANTONG');
insert into AirportCode VALUES(null,'南阳','NNY','ZHNY','南阳姜营机场','NANYANG');
insert into AirportCode VALUES(null,'嫩江','NNN','ZBDY','嫩江机场','HEIHE');
insert into AirportCode VALUES(null,'宁波','NGB','ZSNB','宁波栎社机场','NINGBO');
insert into AirportCode VALUES(null,'且末','IQM','ZWCM','且末机场','QIEMO');
insert into AirportCode VALUES(null,'青岛','TAO','ZSQD','青岛流亭机场','QINGDAO');
insert into AirportCode VALUES(null,'庆阳','IQN','ZLQY','庆阳机场','QINGYANG');
insert into AirportCode VALUES(null,'秦皇岛','SHP','ZBSH','秦皇岛山海关机场','QINHUANGDAO');
insert into AirportCode VALUES(null,'齐齐哈尔','NDG','ZYQQ','齐齐哈尔三家子机场','QIQIHAER');
insert into AirportCode VALUES(null,'衢州','JUZ','ZSJU','衢州机场','QUZHOU');
insert into AirportCode VALUES(null,'三亚','SYX','ZJSY','三亚凤凰机场','SANYA');
insert into AirportCode VALUES(null,'上海','SHA','ZSSS','上海虹桥机场','SHANGHAI');
insert into AirportCode VALUES(null,'上海浦东','PVG','ZSPD','上海浦东机场','SHANGHAI');
insert into AirportCode VALUES(null,'揭阳','SWA','ZGOW','揭阳潮汕机场','JIEYANG');
insert into AirportCode VALUES(null,'沙市','SHS','ZHSS','荆州沙市机场','SHASHI');
insert into AirportCode VALUES(null,'深圳','SZX','ZGSZ','深圳宝安机场','SHENZHEN');
insert into AirportCode VALUES(null,'沈阳','SHE','ZYTX','沈阳桃仙机场','SHENYANG');
insert into AirportCode VALUES(null,'石家庄','SJW','ZBSJ','石家庄正定机场','SHIJIAZHUANG');
insert into AirportCode VALUES(null,'普洱','SYM','ZPSM','普洱(思茅)机场','PUER');
insert into AirportCode VALUES(null,'苏州','SZV','ZSSZ','苏州机场','SUZHOU');
insert into AirportCode VALUES(null,'塔城','TCG','ZWTC','塔城机场','TACHENG');
insert into AirportCode VALUES(null,'太原','TYN','ZBYN','太原武宿机场','TAIYUAN');
insert into AirportCode VALUES(null,'天津','TSN','ZBTJ','天津滨海机场','TIANJIN');
insert into AirportCode VALUES(null,'通化','TNH','ZYTN','通化机场','TONGHUA');
insert into AirportCode VALUES(null,'通辽','TGO','ZBTL','通辽机场','TONGLIAO');
insert into AirportCode VALUES(null,'铜仁','TEN','ZUTR','铜仁凤凰机场','TONGREN');
insert into AirportCode VALUES(null,'万州','WXN','ZUWX','重庆万州五桥机场','CHONGQING');
insert into AirportCode VALUES(null,'潍坊','WEF','ZSWF','潍坊机场','WEIFANG');
insert into AirportCode VALUES(null,'威海','WEH','ZSWH','威海文登大水泊机场','WEIHAI');
insert into AirportCode VALUES(null,'温州','WNZ','ZSWZ','温州永强机场','WENZHOU');
insert into AirportCode VALUES(null,'武汉','WUH','ZHHH','武汉天河机场','WUHAN');
insert into AirportCode VALUES(null,'卡塔赫纳','CTG','','卡塔赫纳机场','CARTAGENA');
insert into AirportCode VALUES(null,'乌兰浩特','HLH','ZBUL','乌兰浩特机场','ULANHOT');
insert into AirportCode VALUES(null,'乌鲁木齐','URC','ZWWW','乌鲁木齐地窝堡机场','URUMQI');
insert into AirportCode VALUES(null,'武夷山','WUS','ZSWY','武夷山机场','WUYISHAN');
insert into AirportCode VALUES(null,'梧州','WUZ','ZGWZ','广西梧州长洲岛机场','WUZHOU');
insert into AirportCode VALUES(null,'厦门','XMN','ZSAM','厦门高崎机场','XIAMEN');
insert into AirportCode VALUES(null,'西安','XIY','ZLXY','西安咸阳机场','XIAN');
insert into AirportCode VALUES(null,'襄阳','XFN','ZHXF','襄阳刘集机场','XIANGYANG');
insert into AirportCode VALUES(null,'西昌','XIC','ZUXC','西昌青山机场','XICHANG');
insert into AirportCode VALUES(null,'锡林浩特','XIL','ZBXH','锡林浩特机场','XILINHOT');
insert into AirportCode VALUES(null,'西宁','XNN','ZLXN','西宁曹家堡机场','XINING');
insert into AirportCode VALUES(null,'徐州','XUZ','ZSXZ','徐州观音机场','XUZHOU');
insert into AirportCode VALUES(null,'延安','ENY','ZLYA','延安二十里铺机场','YANAN');
insert into AirportCode VALUES(null,'延吉','YNJ','ZYYJ','延吉朝阳川机场','YANJI');
insert into AirportCode VALUES(null,'烟台','YNT','ZSYT','烟台莱山机场','YANTAI');
insert into AirportCode VALUES(null,'宜宾','YBP','ZUYB','宜宾(菜坝)机场','YIBIN');
insert into AirportCode VALUES(null,'宜昌','YIH','ZHYC','宜昌三峡机场','YICHANG');
insert into AirportCode VALUES(null,'银川','INC','ZLIC','银川河东机场','YINCHUAN');
insert into AirportCode VALUES(null,'伊宁','YIN','ZWYN','伊宁机场','YINING');
insert into AirportCode VALUES(null,'义乌','YIW','ZSYW','义乌机场','YIWU');
insert into AirportCode VALUES(null,'榆林','UYN','ZLYL','榆林榆阳机场','YULIN');
insert into AirportCode VALUES(null,'昭通','ZAT','ZPZT','昭通机场','ZHAOTONG');
insert into AirportCode VALUES(null,'湛江','ZHA','ZGZJ','湛江机场','ZHANJIANG');
insert into AirportCode VALUES(null,'郑州','CGO','ZHCC','郑州新郑机场','ZHENGZHOU');
insert into AirportCode VALUES(null,'舟山','HSN','ZSZS','舟山普陀山朱家尖机场','ZHOUSHAN');
insert into AirportCode VALUES(null,'珠海','ZUH','ZGSD','珠海金湾机场','ZHUHAI');
insert into AirportCode VALUES(null,'遵义','ZYI','ZUZY','遵义新舟机场','ZUNYI');
insert into AirportCode VALUES(null,'台北','TSA','RCSS','台北松山机场','TAIBEI');
insert into AirportCode VALUES(null,'桃园','TPE','RCTP','台北桃园机场','TAIBEI');
insert into AirportCode VALUES(null,'台南','TNN','RCNN','台南机场','TAINAN');
insert into AirportCode VALUES(null,'高雄','KHH','RCKH','高雄机场','GAOXIONG');
insert into AirportCode VALUES(null,'台东','TTG','RCFN','台东志航机场','TAIDONG');
insert into AirportCode VALUES(null,'花莲','HUN','RCYU','花莲机场','HUALIAN');
insert into AirportCode VALUES(null,'嘉义','CYI','RCKU','嘉义机场','JIAYI');
insert into AirportCode VALUES(null,'黄金海岸','OOL','YBCG','黄金海岸机场','GOLD COAST');
insert into AirportCode VALUES(null,'九寨沟','JZH','ZUJZ','九寨沟黄龙(九黄）机场','JIUZHAIGOU');
insert into AirportCode VALUES(null,'无锡','WUX','ZSWX','无锡硕放机场','WUXI');
insert into AirportCode VALUES(null,'北京南苑','NAY','ZBNY','北京南苑机场','BEIJING');
insert into AirportCode VALUES(null,'那拉提','NLT','ZWNL','那拉提机场','NALATI');
insert into AirportCode VALUES(null,'林芝','LZY','ZUNZ','林芝机场','NYINGCHI');
insert into AirportCode VALUES(null,'乌海','WUA','ZBUH','乌海机场','WUHAI');
insert into AirportCode VALUES(null,'攀枝花','PZI','ZUZH','攀枝花保安营机场','PANZHIHUA');
insert into AirportCode VALUES(null,'满洲里','NZH','ZBMZ','呼伦贝尔满洲里西郊机场','MANZHOULI');
insert into AirportCode VALUES(null,'康定','KGT','ZUKD','康定机场','KANGDING');
insert into AirportCode VALUES(null,'怀化','HJJ','ZGCJ','怀化芷江机场','HUAIHUA');
insert into AirportCode VALUES(null,'邯郸','HDG','ZBHD','河北邯郸机场机场','HANDAN');
insert into AirportCode VALUES(null,'盐城','YNZ','ZSYN','江苏盐城南洋机场','YANCHENG');
insert into AirportCode VALUES(null,'安顺','AVA','ZUAS','贵州安顺黄果树机场','ANSHUN');
insert into AirportCode VALUES(null,'百色','AEB','ZGBS','广西百色(田阳)机场','BAISE');
insert into AirportCode VALUES(null,'文山','WNH','ZPWS','云南文山普者黑机场','WENSHAN');
insert into AirportCode VALUES(null,'玉树','YUS','ZLYS','青海玉树三江源(巴塘)机场','YUSHU');
insert into AirportCode VALUES(null,'荔波','LLB','ZULB','荔波机场','LIBO');
insert into AirportCode VALUES(null,'喀纳斯','KJI','ZWKN','新疆喀纳斯机场','BUERJIN');
insert into AirportCode VALUES(null,'鄂尔多斯','DSN','ZBDS','鄂尔多斯伊金霍洛机场','ORDOS');
insert into AirportCode VALUES(null,'黎平','HZH','ZUNP','贵州黎平机场','LIPING');
insert into AirportCode VALUES(null,'漠河','OHE','ZYMH','漠河古莲机场','MOHE');
insert into AirportCode VALUES(null,'长白山','NBS','ZYBS','长白山机场','CHANGBAISHAN');
insert into AirportCode VALUES(null,'腾冲','TCZ','ZUTC','腾冲（驼峰）机场','TENGCHONG');
insert into AirportCode VALUES(null,'中卫','ZHY','ZLZW','中卫(香山、沙坡头)机场','ZHONGWEI');
insert into AirportCode VALUES(null,'运城','YCU','ZBYC','运城关公机场','YUNCHENG');
insert into AirportCode VALUES(null,'东营','DOY','ZSDY','东营胜利机场','DONGYING');
insert into AirportCode VALUES(null,'天水','THQ','ZLTS','甘肃天水机场','TIANSHUI');
insert into AirportCode VALUES(null,'长海','CNI','ZYCH','长海（大长山岛）机场','DALIAN');
insert into AirportCode VALUES(null,'兴义','ACX','ZUYI','兴义机场','XINGYI');
insert into AirportCode VALUES(null,'首尔','ICN','RKSI','首尔仁川机场','SEOUL');
insert into AirportCode VALUES(null,'济州岛','CJU','RKPC','济州机场','JEJU');
insert into AirportCode VALUES(null,'釜山','PUS','RKPP','金海机场','BUSAN');
insert into AirportCode VALUES(null,'大邱','TAE','RKTN','大邱机场','TAEGU');
insert into AirportCode VALUES(null,'大阪','KIX','RJBB','关西机场','OSAKA');
insert into AirportCode VALUES(null,'东京成田','NRT','RJAA','东京成田机场','TOKYO');
insert into AirportCode VALUES(null,'名古屋','NGO','RJGG','名古屋中部/新特丽亚机场','NAGOYA');
insert into AirportCode VALUES(null,'福冈','FUK','RJFF','福冈机场','FUKUOKA');
insert into AirportCode VALUES(null,'马累','MLE','VRMM','马累机场','MALE');
insert into AirportCode VALUES(null,'普吉岛','HKT','VTSP','普吉机场','PHUKET ISLAND');
insert into AirportCode VALUES(null,'雅加达','CGK','WIII','雅加达 苏加诺-哈达机场','JAKARTA');
insert into AirportCode VALUES(null,'孟买','BOM','VABB','孟买机场','BOMBAY');
insert into AirportCode VALUES(null,'加尔各答','CCU','VECC','加尔各答机场','CALCUTTA');
insert into AirportCode VALUES(null,'新德里','DEL','VIDP','德里机场','NEWDELHI');
insert into AirportCode VALUES(null,'棉兰','MES','WIMM','棉兰机场','MEDAN');
insert into AirportCode VALUES(null,'巴格达','BGW','ORBS','巴格达机场','IRAQ');
insert into AirportCode VALUES(null,'德黑兰','THR','OIII','德黑兰机场','TEHRAN');
insert into AirportCode VALUES(null,'特拉维夫','TLV','LLBG','特拉维夫机场','TEL AVIV');
insert into AirportCode VALUES(null,'曼谷','BKK','VTBS','曼谷(素万那普)机场','BANGKOK');
insert into AirportCode VALUES(null,'新加坡','SIN','WSSS','樟宜机场','SINGAPORE');
insert into AirportCode VALUES(null,'罗马','FCO','LIRF','菲乌米奇诺机场','ROME');
insert into AirportCode VALUES(null,'巴黎','CDG','LFPG','戴高乐机场','PARIS');
insert into AirportCode VALUES(null,'曼彻斯特','MAN','EGCC','曼彻斯特机场','MANCHEST');
insert into AirportCode VALUES(null,'布拉茨克','BTK','UIBB','布拉茨克机场','BRATSK');
insert into AirportCode VALUES(null,'伊尔库茨克','IKT','UIII','伊尔库茨克机场','IRKUTSK');
insert into AirportCode VALUES(null,'威尼斯','VCE','LIPZ','威尼斯机场','VENICE');
insert into AirportCode VALUES(null,'米兰','MXP','LIMC','米兰马尔本萨机场','MILAN');
insert into AirportCode VALUES(null,'那不勒斯','NAP','LIRN','那不勒斯机场','NAPLES');
insert into AirportCode VALUES(null,'马德里','MAD','LEMD','马德里机场','MADRID');
insert into AirportCode VALUES(null,'巴塞罗那','BCN','LEBL','巴塞罗那机场','BARCELONA');
insert into AirportCode VALUES(null,'布达佩斯','BUD','LHBP','布达佩斯机场','BUDAPEST');
insert into AirportCode VALUES(null,'奥克兰','AKL','NZAA','奥克兰机场','AUCKLAND');
insert into AirportCode VALUES(null,'惠灵顿','WLG','NZWN','惠灵顿机场','WELLINGTON');
insert into AirportCode VALUES(null,'雅典','ATH','WBSB','雅典机场','ATHENS');
insert into AirportCode VALUES(null,'塔什干','TAS','UTTT','塔什干机场','TASHKENT');
insert into AirportCode VALUES(null,'斯里巴加湾','BWN','WBSB','文莱机场','BANDAR SERI BEGAWAN');
insert into AirportCode VALUES(null,'伊斯坦布尔','IST','LTBA','阿塔图尔克机场','ISTANBUL');
insert into AirportCode VALUES(null,'喀土穆','KRT','HSSS','喀土穆机场','KHARTOUM');
insert into AirportCode VALUES(null,'达喀尔','DKR','GOOY','达喀尔机场','DAKAR');
insert into AirportCode VALUES(null,'乌兰巴托','ULN','ZMUB','乌兰巴托机场','ULANBUTOR');
insert into AirportCode VALUES(null,'墨西哥','MEX','MMMX','墨西哥城机场','MEXICO');
insert into AirportCode VALUES(null,'吉隆坡','KUL','WMKK','吉隆坡机场','KUALA LUMPUR');
insert into AirportCode VALUES(null,'万象','VTE','VLVT','万象瓦岱机场','VIENTIANE');
insert into AirportCode VALUES(null,'贝鲁特','BEY','OLBA','贝鲁特机场','BEIRUT');
insert into AirportCode VALUES(null,'胡志明市','SGN','VVTS','胡志明市机场','HOCHIMINHCITY');
insert into AirportCode VALUES(null,'苏瓦','SUV','NFNA','苏瓦那机场','SUVA');
insert into AirportCode VALUES(null,'卢森堡','LUX','ELLX','卢森堡机场','LUXEMBOURG');
insert into AirportCode VALUES(null,'科威特','KWI','OKBK','科威特机场','KUWAIT');
insert into AirportCode VALUES(null,'金边','PNH','VDPP','金边机场','PHNOMPENH');
insert into AirportCode VALUES(null,'渥太华','YOW','CYOW','渥太华机场','OTTAWA');
insert into AirportCode VALUES(null,'清州','CJJ','RKTU','清州机场','CHUNGJU');
insert into AirportCode VALUES(null,'温哥华','YVR','CYVR','温哥华机场','VANCOUVER');
insert into AirportCode VALUES(null,'多伦多','YTZ','CYTZ','多伦多市中心机场','TORONTO');
insert into AirportCode VALUES(null,'多伦多','YYZ','CYYZ','多伦多皮尔逊机场','TORONTO');
insert into AirportCode VALUES(null,'蒙特利尔','YMQ','CYUL','蒙特利尔机场','MONTREAL');
insert into AirportCode VALUES(null,'杜塞尔多夫','DUS','EDDL','杜塞尔多夫机场','DUSSELDORF');
insert into AirportCode VALUES(null,'不来梅','BRE','EDDW','不来梅机场','BREMEN');
insert into AirportCode VALUES(null,'柏林','TXL','EDDT','泰格尔机场','BERLIN');
insert into AirportCode VALUES(null,'柏林','THF','EDDI','滕伯尔霍夫机场','BERLIN');
insert into AirportCode VALUES(null,'法兰克福','FRA','EDDF','法兰克福机场','FRANKFURT');
insert into AirportCode VALUES(null,'柏林','SXF','EDDB','舍讷费尔德机场','BERLIN');
insert into AirportCode VALUES(null,'慕尼黑','MUC','EDDM','慕尼黑机场','MUNICH');
insert into AirportCode VALUES(null,'科隆','CGN','EDDK','科隆机场','COLOGNE');
insert into AirportCode VALUES(null,'汉堡','HAM','EDDH','汉堡机场','HAMBURG');
insert into AirportCode VALUES(null,'莫斯科','SVO','UUEE','谢诺梅杰沃机场','MOSCOW');
insert into AirportCode VALUES(null,'莫斯科','DME','UUDD','多莫杰多沃机场','MOSCOW');
insert into AirportCode VALUES(null,'莫斯科','VKO','UUWW','伏努科沃机场','MOSCOW');
insert into AirportCode VALUES(null,'圣彼得堡','LED','ULLI','圣彼得堡机场','SAINT PETERSBURG');
insert into AirportCode VALUES(null,'赤塔','HTA','UIAA','赤塔机场','CHITA');
insert into AirportCode VALUES(null,'哈巴罗夫斯克','KHV','UHHH','伯力机场','KHABAROVSK');
insert into AirportCode VALUES(null,'哥本哈根','CPH','EKCH','哥本哈根机场','COPENHAGEN');
insert into AirportCode VALUES(null,'平壤','FNJ','ZKPY','平壤机场','NIMES');
insert into AirportCode VALUES(null,'华沙','WAW','EPWA','华沙萧邦机场','WARSAW');
insert into AirportCode VALUES(null,'悉尼','SYD','YSSY','悉尼金斯福德?史密斯机场','SYDNEY');
insert into AirportCode VALUES(null,'墨尔本','MEL','YMML','墨尔本机场','MELBOURNE');
insert into AirportCode VALUES(null,'堪培拉','CBR','YSCB','堪培拉机场','CANBERRA');
insert into AirportCode VALUES(null,'维也纳','VIE','LOWW','维也纳机场','VIENNA');
insert into AirportCode VALUES(null,'都柏林','DUB','EIDW','都柏林机场','DUBLIN');
insert into AirportCode VALUES(null,'亚的斯亚贝巴','ADD','HAAB','亚的斯亚贝巴机场','ADDIS ABABA');
insert into AirportCode VALUES(null,'开罗','CAI','HECA','开罗机场','CAIRO');
insert into AirportCode VALUES(null,'阿斯旺','ASW','HESN','阿斯旺机场','ASWAN');
insert into AirportCode VALUES(null,'圣保罗','GRU','SBSP','圣保罗机场','SAO PAULO');
insert into AirportCode VALUES(null,'巴西利亚','BSB','SBBR','巴西利亚机场','BRASíLIA');
insert into AirportCode VALUES(null,'巴拿马城','PTY','MPMG','巴拿马城机场','PANAMACITY');
insert into AirportCode VALUES(null,'伊斯兰堡','ISB','OPRN','伊斯兰堡机场','ISLAMABAD');
insert into AirportCode VALUES(null,'卡拉奇','KHI','OPKC','卡拉奇机场','KARACHI');
insert into AirportCode VALUES(null,'沙迦','SHJ','OMSJ','莎迦机场','SHARJAH');
insert into AirportCode VALUES(null,'喀布尔','KBL','OAKB','喀布尔机场','KABUL');
insert into AirportCode VALUES(null,'阿尔及尔','ALG','DAAG','阿尔及尔机场','ALGIERS');
insert into AirportCode VALUES(null,'布鲁塞尔','BRU','EBBR','布鲁塞尔机场','BRUSSELS');
insert into AirportCode VALUES(null,'鹿特丹','RTM','EHRD','鹿特丹机场','ROTTERDAM');
insert into AirportCode VALUES(null,'日内瓦','GVA','LSGG','日内瓦机场','GENEVA');
insert into AirportCode VALUES(null,'斯德哥尔摩','ARN','ESSA','斯德哥尔摩机场','STOCKHOLM');
insert into AirportCode VALUES(null,'突尼斯','TUN','DTTA','突尼斯机场','TUNIS');
insert into AirportCode VALUES(null,'加拉加斯','CCS','SVFM','加拉加斯机场','CARACAS');
insert into AirportCode VALUES(null,'危地马拉城','GUA','MGGT','危地马拉城机场','GUATEMALACITY');
insert into AirportCode VALUES(null,'大马士革','DAM','OSDI','大马士革机场','DAMASCUS');
insert into AirportCode VALUES(null,'里昂','LYS','LFLL','里昂机场','LYON');
insert into AirportCode VALUES(null,'圣地亚哥','SCL','SCEL','圣地亚哥机场','SANTIAGO');
insert into AirportCode VALUES(null,'哥德堡','GOT','ESGP','哥德堡机场','GOTHENBURG');
insert into AirportCode VALUES(null,'仙台','SDJ','FAYP','仙台机场','SANDAI');
insert into AirportCode VALUES(null,'千岁','CTS','RJCJ','千岁机场','CHITOSE');
insert into AirportCode VALUES(null,'里斯本','LIS','RJSS','里斯本机场','LISBON');
insert into AirportCode VALUES(null,'奥斯陆','OSL','ENGM','奥斯陆机场','OSLO');
insert into AirportCode VALUES(null,'拉各斯','LOS','DNMM','拉各斯机场','LAGOS');
insert into AirportCode VALUES(null,'拉巴特','RBA','GMME','拉巴特机场','RABAT');
insert into AirportCode VALUES(null,'开普敦','CPT','FAYP','开普顿机场','CAPE TOWN');
insert into AirportCode VALUES(null,'约翰内斯堡','JNB','FAJS','约翰内斯堡机场','JOHANNESBURG');
insert into AirportCode VALUES(null,'休斯顿','HOU','KHOU','休斯顿机场','HOUSTON');
insert into AirportCode VALUES(null,'檀香山','HNL','PHNL','檀香山机场','HONOLULU');
insert into AirportCode VALUES(null,'芝加哥','ORD','KORD','芝加哥机场','CHICAGO');
insert into AirportCode VALUES(null,'纽约','JFK','KJFK','肯尼迪机场','NEW YORK');
insert into AirportCode VALUES(null,'波士顿','BOS','KBOS','波士顿机场','BOSTON');
insert into AirportCode VALUES(null,'洛杉矶','LAX','KLAX','洛杉矶机场','LOS ANGELES');
insert into AirportCode VALUES(null,'华盛顿','WAS','KWAS','华盛顿机场','WASHINGTON');
insert into AirportCode VALUES(null,'底特律','DTT','KDTT','底特律机场','DETROIT');
insert into AirportCode VALUES(null,'迈阿密','MIA','KMIA','迈阿密机场','MIAMI');
insert into AirportCode VALUES(null,'费城','PHL','KPHL','费城机场','PHILADELPHIA');
insert into AirportCode VALUES(null,'西雅图','SEA','KSEA','西雅图机场','SEATTLE');
insert into AirportCode VALUES(null,'旧金山','SFO','KSFO','旧金山机场','SAN FRANCISCO');
insert into AirportCode VALUES(null,'索非亚','SOF','LBSF','索非亚机场','SOFIA');
insert into AirportCode VALUES(null,'阿姆斯特丹','AMS','EHAM','荷兰阿姆斯特丹斯史基浦(西霍普)机场','AMSTERDAM');
insert into AirportCode VALUES(null,'阿拉木图','ALA','UAAA','阿拉木图机场','ALMAATA');
insert into AirportCode VALUES(null,'马尼拉','MNL','RPLL','马尼拉机场','MANILA');
insert into AirportCode VALUES(null,'赫尔辛基','HEL','EFHK','赫尔辛基机场','HELSINKI');
insert into AirportCode VALUES(null,'波哥大','BOG','SKBO','波哥大机场','BOGOTA');
insert into AirportCode VALUES(null,'利马','LIM','LIMA','利马机场','LIMA');
insert into AirportCode VALUES(null,'达卡','DAC','VGZR','齐亚机场','DACCA');
insert into AirportCode VALUES(null,'长滩','LGB','KLGB','长滩机场','LONGBEACH');
insert into AirportCode VALUES(null,'伦敦','LHR','EGLL','伦敦希思罗机场','LONDON');
insert into AirportCode VALUES(null,'实里达','XSP','WSSL','实里达机场','SELETAR');
insert into AirportCode VALUES(null,'丹佛','DEN','KDEN','丹佛机场','DENVER');
insert into AirportCode VALUES(null,'加德满都','KTM','VNKT','加德满都机场','KATHMANDU');
insert into AirportCode VALUES(null,'登巴萨','DPS','WADD','巴厘岛机场','DENPASAR');
insert into AirportCode VALUES(null,'龙岩','LCX','ZSLO','福建龙岩冠豸山机场','LONGYAN');
insert into AirportCode VALUES(null,'加利福尼亚州','BLH','KBLH','加利福尼亚布莱斯机场','CALIFORNIA');
insert into AirportCode VALUES(null,'希拉本德','BDN','KBDN','希拉本德机场','GILA BEND');
insert into AirportCode VALUES(null,'巴吞鲁日','BTR','KBTR','巴吞鲁日(瑞安)机场','BATON ROUGE');
insert into AirportCode VALUES(null,'曼谷','DMK','VTBD','廊曼机场','BANGKOK');
insert into AirportCode VALUES(null,'苏黎世','ZRH','LSZH','苏黎世机场','ZURICH');
insert into AirportCode VALUES(null,'利物浦','LPL','EGGP','利物浦约翰列侬机场','LIVERPOOL');
insert into AirportCode VALUES(null,'伯明翰','BHX','EGBB','伯明翰机场','BIRMINGHAM');
insert into AirportCode VALUES(null,'科伦坡','CMB','VCBI','班达拉奈克机场','COLOMBO');
insert into AirportCode VALUES(null,'仰光','RGN','VYYY','仰光机场','YANGON');
insert into AirportCode VALUES(null,'古德伊尔','GYR','KGYR','菲尼克斯古德伊尔机场','GOODYEAR');
insert into AirportCode VALUES(null,'Pinal','MZJ','KMZJ','皮纳尔飞机坟场机场','PINAL COUNTY');
insert into AirportCode VALUES(null,'圣马丁','SXM','TNCM','朱利安娜公主机场','ST. MAARTEN');
insert into AirportCode VALUES(null,'Ryan Field','RYN','KRYN','Ryan Field机场','RYAN FIELD');
insert into AirportCode VALUES(null,'大庆','DQA','ZYDQ','大庆萨尔图机场','DAQING');
insert into AirportCode VALUES(null,'布宜诺斯艾利斯','BUE','','布宜诺斯艾利斯机场','BUENOS AIRES');
insert into AirportCode VALUES(null,'古晋','KCH','','古晋机场','KUCHING');
insert into AirportCode VALUES(null,'沙巴','BKI','','沙巴机场','SABAH');
insert into AirportCode VALUES(null,'槟城','PEN','','槟城机场','PENANG');
insert into AirportCode VALUES(null,'印第安纳波利斯','IND','KIND','印第安纳波利斯机场','INDIANAPOLIS');
insert into AirportCode VALUES(null,'维斯特切斯特郡','HPN','','维斯特切斯特郡机场','WESTCHESTER COUNTY');
insert into AirportCode VALUES(null,'盐湖城','SLC','','盐湖城机场','SALT LAKE CITY');
insert into AirportCode VALUES(null,'俄克拉荷马城','OKC','','俄克拉荷马城机场','WILL ROGERS');
insert into AirportCode VALUES(null,'斯波坎','GEG','','斯波坎机场','SPOKANE');
insert into AirportCode VALUES(null,'圣迭戈','SAN','','圣迭戈机场','SAN DIEGO');
insert into AirportCode VALUES(null,'圣安东尼奥','SAT','','圣安东尼奥机场','SAN ANTONIO');
insert into AirportCode VALUES(null,'休斯敦','IAH','','休斯敦机场','GEORGE BUSH');
insert into AirportCode VALUES(null,'孟菲斯','MEM','KMEM','孟菲斯机场','MEMPHIS');
insert into AirportCode VALUES(null,'拉斯维加斯','LAS','KLAS','拉斯维加斯麦卡伦国际机场机场','MCCARRAN');
insert into AirportCode VALUES(null,'里士满','RIC','','里士满机场','RICHMOND');
insert into AirportCode VALUES(null,'莫林','MLI','','莫林机场','QUAD-CITY');
insert into AirportCode VALUES(null,'考爱岛','LIH','','考爱岛机场','KAUAI ISLAND');
insert into AirportCode VALUES(null,'堪萨斯城','MCI','','堪萨斯城机场','KANSAS CITY');
insert into AirportCode VALUES(null,'哈里斯堡','MDT','','哈里斯堡机场','HARRISBURG SKYPORT');
insert into AirportCode VALUES(null,'得梅因','DSM','','得梅因机场','DES MOINES');
insert into AirportCode VALUES(null,'列克星敦','LEX','','列克星敦机场','ORLANDO');
insert into AirportCode VALUES(null,'奥兰多','MCO','KMCO','奥兰多机场','AOKELAN');
insert into AirportCode VALUES(null,'杰克逊维尔','JAX','KJAX','杰克逊维尔机场','JACKSONVILLE');
insert into AirportCode VALUES(null,'布法罗','BUF','KBUF','布法罗机场','BUFFALO');
insert into AirportCode VALUES(null,'亚特兰大','ATL','KATL','亚特兰大机场','ATLANTA');
insert into AirportCode VALUES(null,'圣路易斯','STL','','圣路易斯机场','SAINT LOUIS');
insert into AirportCode VALUES(null,'波特兰','PDX','','波特兰机场','PORTLAND');
insert into AirportCode VALUES(null,'曼德勒','MDL','VYMD','曼德勒机场','曼德勒');
insert into AirportCode VALUES(null,'波尔图','OPO','','波尔图机场','PORTO');
insert into AirportCode VALUES(null,'冲绳','OKA','ROAH','那霸机场','OKINAWA');
insert into AirportCode VALUES(null,'东京','TYO','','东京机场','TOKYO');
insert into AirportCode VALUES(null,'札幌','SPK','','札幌机场','SAPPORO');
insert into AirportCode VALUES(null,'塞班','SPN','PGSN','塞班机场','NORTHERN MARIANA ISLANDS');
insert into AirportCode VALUES(null,'伯尔尼','BRN','LSZB','伯尔尼机场','BERNE');
insert into AirportCode VALUES(null,'苏梅岛','USM','VTSM','苏梅岛机场','KOH SAMUI');
insert into AirportCode VALUES(null,'基辅','IEV','','基辅机场','KIEV');
insert into AirportCode VALUES(null,'基督城','CHC','','基督城机场','CHRISTCHURCH');
insert into AirportCode VALUES(null,'耶路撒冷','JRS','','耶路撒冷机场','JERUSALEM');
insert into AirportCode VALUES(null,'都灵','TRN','','都灵机场','TURIN');
insert into AirportCode VALUES(null,'罗马','ROM','','罗马机场','ROME');
insert into AirportCode VALUES(null,'佛罗伦萨','FLR','','佛罗伦萨机场','FLORENCE');
insert into AirportCode VALUES(null,'班加罗尔','BLR','','班加罗尔机场','BANGALORE');
insert into AirportCode VALUES(null,'泗水','SUB','WARR','朱安达泗水机场','SURABAYA');
insert into AirportCode VALUES(null,'爱丁堡','EDI','','爱丁堡机场','EDINBURGH');
insert into AirportCode VALUES(null,'利兹','LBA','','利兹机场','LEEDS');
insert into AirportCode VALUES(null,'格拉斯哥','GLA','','格拉斯哥机场','GLASGOW');
insert into AirportCode VALUES(null,'安曼','AMM','OJAI','安曼阿莉娅王后机场','AMMAN');
insert into AirportCode VALUES(null,'河内','HAN','','河内机场','HANOI');
insert into AirportCode VALUES(null,'多哈','DOH','OTBD','多哈机场','DOH');
insert into AirportCode VALUES(null,'布拉格','PRG','','布拉格机场','PRAGUE');
insert into AirportCode VALUES(null,'温尼伯','YWG','CYWG','温尼伯机场','DELINE');
insert into AirportCode VALUES(null,'维多利亚','YYJ','CYYJ','维多利亚机场','VICTORIA');
insert into AirportCode VALUES(null,'魁北克','YQB','CYQB','魁北克城机场','QUEBEC');
insert into AirportCode VALUES(null,'暹粒','REP','VDSR','暹粒吴哥机场','ANGKOR WAT');
insert into AirportCode VALUES(null,'暹粒','REP','VDSR','暹粒吴哥机场','ANGKOR WAT');
insert into AirportCode VALUES(null,'全州','CHN','','全州机场','JEONJU');
insert into AirportCode VALUES(null,'宿雾','CEB','','宿雾机场','CEBU');
insert into AirportCode VALUES(null,'巴黎','PAR','','巴黎机场','PARIS');
insert into AirportCode VALUES(null,'符拉迪沃斯托克','VVO','UHWW','符拉迪沃斯托克机场','VLADIVOSTOK');
insert into AirportCode VALUES(null,'莫斯科','MOW','','莫斯科机场','MOSCOW');
insert into AirportCode VALUES(null,'纽伦堡','NUE','EDDN','纽伦堡机场','NUREMBERG');
insert into AirportCode VALUES(null,'迪拜','DXB','OMDB','迪拜机场','DUBAI');
insert into AirportCode VALUES(null,'阿布扎比','AUH','','阿布扎比机场','ABU DHABI');
insert into AirportCode VALUES(null,'亚历山大','ALY','','亚历山大机场','ALEXANDRIA');
insert into AirportCode VALUES(null,'阿德莱德','ADL','YPAD','阿德莱德机场','ADELAIDE');
insert into AirportCode VALUES(null,'珀斯','PER','YPPH','珀斯机场','PERTH');
insert into AirportCode VALUES(null,'布里斯班','BNE','YBBN','布里斯班机场','BRISBANE');
insert into AirportCode VALUES(null,'达尔文','DRW','YPDN','达尔文机场','DARWIN');
insert into AirportCode VALUES(null,'鸡西','JXA','ZYJX','鸡西兴凯湖机场','JIXI');
insert into AirportCode VALUES(null,'永州','LLF','ZGLG','湖南永州零陵机场','YONGZHOU');
insert into AirportCode VALUES(null,'韶关','HSC','','韶关机场','SHAOGUAN');
insert into AirportCode VALUES(null,'井冈山','JGS','ZSGS','井冈山机场','JINGGANGSHAN');
insert into AirportCode VALUES(null,'阜阳','FUG','ZSFY','阜阳西关机场','FUYANG');
insert into AirportCode VALUES(null,'凯恩斯','CNS','YBCS','凯恩斯机场','CAIRNS');
insert into AirportCode VALUES(null,'蓬塔卡纳','PUJ','MDPC','蓬塔卡纳机场','PUNTA CA NA');
insert into AirportCode VALUES(null,'二连浩特','ERL','ZBER','二连浩特赛乌苏国际机场','ERLIANHOT');
insert into AirportCode VALUES(null,'广元','GYS','ZUGU','广元机场','GUANGYUAN');
insert into AirportCode VALUES(null,'佛山','FUO','ZGFS','佛山沙堤机场','FOSHAN');
insert into AirportCode VALUES(null,'吉安','KNC','ZSJA','吉安机场','JIAN');
insert into AirportCode VALUES(null,'博韦','BVA','LFOB','博韦蒂耶机场','BEAUVAIS');
insert into AirportCode VALUES(null,'伊春','LDS','ZYLD','伊春林都机场','YICHUN');
insert into AirportCode VALUES(null,'安卡拉','ANK','','安卡拉(首都)机场','ANKARA');
insert into AirportCode VALUES(null,'安卡拉','ESB','LTAC','安卡拉埃森博阿机场','ANKARA');
insert into AirportCode VALUES(null,'吐鲁番','TLQ','ZWTL','吐鲁番交河机场','TULUFAN');
insert into AirportCode VALUES(null,'东京羽田','HND','RJTT','东京羽田国际机场','TOKYO');
insert into AirportCode VALUES(null,'达拉斯','DFW','KDFW','达拉斯沃尔斯堡机场','DALLAS');
insert into AirportCode VALUES(null,'固原','GYU','ZLGY','宁夏固原六盘山机场','GUYUAN');
insert into AirportCode VALUES(null,'金门','KNH','RCBS','尚义机场','JINMEN');
insert into AirportCode VALUES(null,'马公','MZG','RCQC','马公机场','PENGHU');
insert into AirportCode VALUES(null,'金浦','GMP','RKSS','首尔金浦国际机场','SEOUL');
insert into AirportCode VALUES(null,'墨尔本','AVV','YMAV','爱华隆机场','MELBOURNE');
insert into AirportCode VALUES(null,'马拉加','AGP','LEMG','马拉加机场','MALAGA');
insert into AirportCode VALUES(null,'奥什','OSS','UAFO','奥什机场','OSH STATE');
insert into AirportCode VALUES(null,'奥尔代斯','ADY','FAAL','奥尔代斯机场','ALLDAYS');
insert into AirportCode VALUES(null,'萨凡纳','SAV','KSAV','萨凡纳机场','SAVANNAH');
insert into AirportCode VALUES(null,'扬斯顿','YNG','KYNG','扬斯顿机场','YOUNGSTOWN-WARREN REGIONAL');
insert into AirportCode VALUES(null,'台中','RMQ','RCMQ','台中清泉岗机场','TAIZHONG');
insert into AirportCode VALUES(null,'屏东','PIF','RCDC','屏东机场','PINGDONG');
insert into AirportCode VALUES(null,'恒春','HCN','RCKW','恒春五里亭机场','PINGDONG');
insert into AirportCode VALUES(null,'邢台','XNT','ZBXT','邢台褡裢机场','SHAHE');
insert into AirportCode VALUES(null,'兴城','XEN','ZYXC','兴城机场','HULUDAO');
insert into AirportCode VALUES(null,'安阳','AYN','ZHAY','安阳北郊机场','ANYANG');
insert into AirportCode VALUES(null,'北竿','MFK','RCMT','北竿机场','北竿');
insert into AirportCode VALUES(null,'连江','LZN','RCFG','南竿机场','LIANJIANG NANGAN');
insert into AirportCode VALUES(null,'七美','CMJ','RCCM','七美机场','QIMEI');
insert into AirportCode VALUES(null,'多森','DHN','KDHN','多森机场','DOTHAN');
insert into AirportCode VALUES(null,'亨茨维尔','HSV','KHSV','亨茨维尔机场','HUNTSVILLE');
insert into AirportCode VALUES(null,'莫比尔','MOB','KMOB','莫比尔机场','MOBILE');
insert into AirportCode VALUES(null,'蒙哥马利','MGM','KMGM','蒙哥马利机场','MONTGOMERY');
insert into AirportCode VALUES(null,'阿拉巴马','MSL','KMSL','阿拉巴马西北机场','ALABAMA');
insert into AirportCode VALUES(null,'安克雷奇','ANC','PANC','泰德?史蒂文斯安克雷奇机场','ANCHORAGE');
insert into AirportCode VALUES(null,'巴黎','ORY','LFPO','巴黎－奥利机场','PARIS');
insert into AirportCode VALUES(null,'巴塞尔','BSL','LFSB','巴塞尔米卢斯弗赖堡机场','BASEL');
insert into AirportCode VALUES(null,'图卢兹','TLS','LFBO','图卢兹布拉尼亚克机场','TOULOUSE');
insert into AirportCode VALUES(null,'斯特拉斯堡','SXB','LFST','斯特拉斯堡机场','STRASBOURG');
insert into AirportCode VALUES(null,'尼斯','NCE','LFMN','尼斯蓝色海岸机场','NICE');
insert into AirportCode VALUES(null,'马赛','MRS','LFML','马赛普罗旺斯机场','MARSEILLES');
insert into AirportCode VALUES(null,'木浦','MWX','RKJB','务安机场','MUAN');
insert into AirportCode VALUES(null,'纽卡斯尔','NCL','EGNT','纽卡斯尔机场','NEWCASTLE');
insert into AirportCode VALUES(null,'里约热内卢','GIG','SBGL','里约热内卢 加利昂机场','RIODEJANEIRO');
insert into AirportCode VALUES(null,'累西腓','REC','SBRF','累西腓瓜拉拉皮斯吉尔贝托?弗雷雷机场','RECIFE');
insert into AirportCode VALUES(null,'里约热内卢','SDU','SBRJ','圣杜蒙特机场','RIODEJANEIRO');
insert into AirportCode VALUES(null,'马瑙斯','MAO','SBEG','马瑙斯爱德华多?戈梅斯机场','MANAUS');
insert into AirportCode VALUES(null,'萨尔瓦多','SSA','SBSV','萨尔瓦多路易斯?爱德华多?马加良斯议员机场','SALVADOR');
insert into AirportCode VALUES(null,'蓬莱','PNJ','ZSPL','蓬莱沙河口机场','YANTAI');
insert into AirportCode VALUES(null,'坎大哈','KDH','OAKN','坎大哈机场','KANDAHAR');
insert into AirportCode VALUES(null,'罗安达','LAD','FNLU','罗安达二月四日机场','LUANDA');
insert into AirportCode VALUES(null,'乌斯怀亚','USH','SAWH','乌斯怀亚 马尔维纳斯机场','USHUAIA');
insert into AirportCode VALUES(null,'布宜诺斯艾利斯','EZE','SAEZ','埃塞萨皮斯塔里尼部长机场','BUENOS AIRES');
insert into AirportCode VALUES(null,'列日','LGG','EBLG','列日机场','LIEGE');
insert into AirportCode VALUES(null,'沙尔勒鲁瓦','CRL','EBCI','沙尔勒鲁瓦 南布鲁塞尔机场','CHARLEROI');
insert into AirportCode VALUES(null,'汉诺威','HAJ','EDDV','汉诺威 朗根哈根机场','HANNOVER');
insert into AirportCode VALUES(null,'德累斯顿','DRS','EDDC','德累斯顿机场','DRESDEN');
insert into AirportCode VALUES(null,'斯图加特','STR','EDDS','斯图加特机场','STUTTGART');
insert into AirportCode VALUES(null,'金奈','MAA','VOMM','金奈机场','CHENNAI');
insert into AirportCode VALUES(null,'特里凡得琅','TRV','VOTV','特里凡得琅机场','TRIVANDRUM');
insert into AirportCode VALUES(null,'那格浦尔','NAG','VANP','索内格翁机场','NAGPUR');
insert into AirportCode VALUES(null,'艾哈迈达巴德','AMD','VAAH','萨达尔?瓦拉巴伊?帕特尔机场','AHMEDABAD');
insert into AirportCode VALUES(null,'函馆','HKD','RJCH','函馆机场','HAKODATE');
insert into AirportCode VALUES(null,'广岛','HIJ','RJOA','广岛机场','HIROSHIMA');
insert into AirportCode VALUES(null,'新泻','KIJ','RJSN','新泻机场','NIIGATA');
insert into AirportCode VALUES(null,'高松','TAK','RJOT','高松机场','TAKAMATSU');
insert into AirportCode VALUES(null,'钏路','KUH','RJCK','钏路机场','KUSHIRO');
insert into AirportCode VALUES(null,'松山','MYJ','RJOM','日本松山机场','MATSUYAMA');
insert into AirportCode VALUES(null,'福冈','KKJ','RJFR','北九州机场','FUKUOKA');
insert into AirportCode VALUES(null,'长崎','NGS','RJFU','长崎机场','NAGASAKI');
insert into AirportCode VALUES(null,'熊本','KMJ','RJFT','熊本机场','KUMAMOTO');
insert into AirportCode VALUES(null,'大分','OIT','RJFO','大分机场','OITA');
insert into AirportCode VALUES(null,'宫崎','KMI','RJFM','宫崎机场','MIYAZAKI');
insert into AirportCode VALUES(null,'鹿儿岛','KOJ','RJFK','鹿儿岛机场','KAGOSHIMA');
insert into AirportCode VALUES(null,'旭川','AKJ','RJEC','旭川机场','ASAHIKAWA');
insert into AirportCode VALUES(null,'带广','OBO','RJCB','带广机场','OBIHIRO');
insert into AirportCode VALUES(null,'秋田','AXT','RJSK','秋田机场','AKITA');
insert into AirportCode VALUES(null,'山口','UBJ','RJDC','山口机场','YAMAGUCHI');
insert into AirportCode VALUES(null,'乌隆他尼','UTH','VTUD','乌隆他尼机场','UDON THANI');
insert into AirportCode VALUES(null,'芭堤雅','UTP','VTBU','乌打抛机场','PATTAYA');
insert into AirportCode VALUES(null,'清迈','CNX','VTCC','清迈机场','CHIANG MAI');
insert into AirportCode VALUES(null,'合艾','HDY','VTSS','合艾机场','HAT YAI');
insert into AirportCode VALUES(null,'伊斯坦布尔','SAW','LTFJ','萨比哈?格克琴机场','ISTANBUL');
insert into AirportCode VALUES(null,'洛美','LFW','DXXX','纳辛贝?埃亚德马机场','LOME');
insert into AirportCode VALUES(null,'达曼','DMM','OEDF','法赫德国王机场','DAMMAM');
insert into AirportCode VALUES(null,'利雅德','RUH','OERK','哈立德国王机场','RIYADH');
insert into AirportCode VALUES(null,'吉达','JED','OEJN','阿卜杜勒-阿齐兹国王机场','JEDDAH');
insert into AirportCode VALUES(null,'麦地那','MED','OEMA','穆罕默德?本?阿卜杜勒-阿齐兹亲王机场','MEDINA');
insert into AirportCode VALUES(null,'姆马巴托','MBD','FAMM','姆马巴托机场','MMABATHO');
insert into AirportCode VALUES(null,'加那利群岛','LPA','GCLP','大加那利机场','ISLAS CANARIAS');
insert into AirportCode VALUES(null,'特内里费','TFN','GCXO','北特内里费机场','TENERIFE');
insert into AirportCode VALUES(null,'明斯克','MSQ','UMMS','明斯克机场','MINSK');
insert into AirportCode VALUES(null,'斯瓦尔巴群岛','LYR','ENSB','斯瓦尔巴朗伊尔机场','SVALBARD');
insert into AirportCode VALUES(null,'萨尔茨堡','SZG','LOWS','萨尔茨堡机场','SALZBURG');
insert into AirportCode VALUES(null,'杜阿拉','DLA','FKKD','杜阿拉机场','DOUALA');
insert into AirportCode VALUES(null,'哈利法克斯','YHZ','CYHZ','哈利法克斯罗伯特?洛恩?斯坦菲尔德机场','HALIFAX');
insert into AirportCode VALUES(null,'萨斯卡通','YXE','CYXE','萨斯卡通约翰?乔治?迪芬贝克机场','SASKATOON');
insert into AirportCode VALUES(null,'怀特霍斯','YXY','CYXY','埃里克?尼尔森怀特霍斯机场','WHITEHORSE');
insert into AirportCode VALUES(null,'哈密尔顿','YHM','CYHM','约翰?卡尔?芒罗哈密尔顿机场','HAMILTON');
insert into AirportCode VALUES(null,'万锦','YKZ','CYKZ','巴顿维尔机场','MARKHAM');
insert into AirportCode VALUES(null,'森讷堡','SGD','EKSB','森讷堡机场','SONDERBORG');
insert into AirportCode VALUES(null,'辛代尔','CNL','EKSN','辛代尔机场','SINDAL');
insert into AirportCode VALUES(null,'艾斯尤特','ATZ','HEAT','艾斯尤特机场','ASSIUT');
insert into AirportCode VALUES(null,'卢克索','LXR','HELX','卢克索机场','LUXOR');
insert into AirportCode VALUES(null,'沙姆沙伊赫','SSH','HESH','沙姆沙伊赫机场','SHARM EL-SHEIKH');
insert into AirportCode VALUES(null,'古尔代盖','HRG','HEGN','古尔代盖机场','HURGHADA');
insert into AirportCode VALUES(null,'阿克拉','ACC','DGAA','科托卡机场','ACCRA');
insert into AirportCode VALUES(null,'凯夫拉维克','KEF','BIKF','凯夫拉维克机场','KEFLAVIK');
insert into AirportCode VALUES(null,'万鸦老','MDC','WAMM','美娜多机场','MANADO');
insert into AirportCode VALUES(null,'比什凯克','FRU','UAFM','马纳斯机场','BISHKEK');
insert into AirportCode VALUES(null,'德黑兰','IKA','OIIE','伊玛目霍梅尼机场','TEHRAN');
insert into AirportCode VALUES(null,'马什哈德','MHD','OIMM','马什哈德机场','MASHHAD');
insert into AirportCode VALUES(null,'设拉子','SYZ','OISS','设拉子机场','SHIRAZ');
insert into AirportCode VALUES(null,'卡塔尼亚','CTA','LICC','丰坦罗撒机场','CATANIA');
insert into AirportCode VALUES(null,'班加西','BEN','HLLB','班加西贝尼纳机场','BENGHAZI');
insert into AirportCode VALUES(null,'埃斯比约','EBJ','EKEB','埃斯比约机场','ESBJERG');
insert into AirportCode VALUES(null,'拉合尔','LHE','OPLA','拉合尔机场','LAHORE');
insert into AirportCode VALUES(null,'白沙瓦','PEW','OPPS','白沙瓦机场','PESHAWAR');
insert into AirportCode VALUES(null,'新西伯利亚','OVB','UNNT','新西伯利亚机场','NOVOSIBIRSK TOLMACHEVO');
insert into AirportCode VALUES(null,'阿里','NGQ','ZUAL','阿里昆莎机场','SHIQUANHE');
insert into AirportCode VALUES(null,'伦敦','LGW','EGKK','盖特威克机场','LONDON');
insert into AirportCode VALUES(null,'纳什维尔','BNA','KBNA','纳什维尔机场','NASHVILLE');
insert into AirportCode VALUES(null,'塔尔萨','TUL','KTUL','塔尔萨机场','TULSA');
insert into AirportCode VALUES(null,'芝加哥','MDW','KMDW','芝加哥中途机场','CHICAGO');
insert into AirportCode VALUES(null,'劳德代尔堡','FLL','KFLL','劳德代尔堡－好莱坞机场','FORT LAUDERDALE');
insert into AirportCode VALUES(null,'奥兰多','SFB','KSFB','奥兰多桑福德机场','AOKELAN');
insert into AirportCode VALUES(null,'巴尔的摩','BWI','KBWI','古德?马歇尔机场','BALTIMORE');
insert into AirportCode VALUES(null,'华盛顿','DCA','KDCA','罗纳德?里根机场','WASHINGTON');
insert into AirportCode VALUES(null,'亚丁','SAH','OYSN','亚丁机场','ADEN');
insert into AirportCode VALUES(null,'奥克兰','OAK','KOAK','加州奥克兰机场','OAKLAND');
insert into AirportCode VALUES(null,'格拉斯哥','PIK','EGPK','普雷斯蒂克机场','GLASGOW');
insert into AirportCode VALUES(null,'贝尔法斯特','BHD','EGAC','乔治?贝斯特贝尔法斯特机场','BELFAST');
insert into AirportCode VALUES(null,'纽瓦克','EWR','KEWR','纽瓦克机场','NEWARK');
insert into AirportCode VALUES(null,'巴戈特维尔','YBG','CYBG','巴戈特维尔机场','BAGOTVILLE');
insert into AirportCode VALUES(null,'麋鹿湖','YAD','CYAD','麋鹿湖机场','MOOSE LAKE');
insert into AirportCode VALUES(null,'弗朗西斯堡','YAG','CYAG','弗朗西斯堡机场','FORT FRANCES');
insert into AirportCode VALUES(null,'拉格兰德','YGL','CYGL','拉格兰德机场','LAGRANDE');
insert into AirportCode VALUES(null,'苏圣玛丽','YAM','CYAM','苏圣玛丽机场','SAULT STE. MARIE');
insert into AirportCode VALUES(null,'哈利法克斯','YAW','CYAW','哈利法克斯机场','HALIFAX');
insert into AirportCode VALUES(null,'图芬奴','YAZ','CYAZ','图芬奴机场','TOFINO');
insert into AirportCode VALUES(null,'佩利湾','YBB','CYBB','佩利湾机场','PELLY BAY');
insert into AirportCode VALUES(null,'贝科莫','YBC','CYBC','贝科莫机场','BAIE COMEAU');
insert into AirportCode VALUES(null,'新威斯敏斯特','YBD','CYBD','新威斯敏斯特机场','NEW WESTMINSTER');
insert into AirportCode VALUES(null,'铀城','YBE','CYBE','铀城机场','URANIUM CITY');
insert into AirportCode VALUES(null,'邦尼维尔','YBF','CYBF','邦尼维尔机场','BONNYVILLE');
insert into AirportCode VALUES(null,'贝克湖','YBK','CYBK','贝克湖机场','BAKER LAKE');
insert into AirportCode VALUES(null,'博登','YBN','CYBN','博登直升机机场','BORDEN');
insert into AirportCode VALUES(null,'茵斯布鲁克','INN','LOWI','茵斯布鲁克机场','INNSBRUCK');
insert into AirportCode VALUES(null,'巴瑟斯特','BHS','YBTH','巴瑟斯特机场','BATHURST');
insert into AirportCode VALUES(null,'卡地克兰','MPH','','卡地克兰机场','CATICLAN');
insert into AirportCode VALUES(null,'神河','ZGI','CZGI','神河机场','GODS RIVER');
insert into AirportCode VALUES(null,'基劳纳','YLW','CYLW','基劳纳机场','KELOWNA');
insert into AirportCode VALUES(null,'圣约翰','YSJ','CYSJ','圣约翰机场','SAINT JOHN');
insert into AirportCode VALUES(null,'乔治皇子','YXS','CYXS','乔治皇子城机场','PRINCE GEORGE');
insert into AirportCode VALUES(null,'萨德伯里','YSB','CYSB','萨德伯里机场','SUDBURY');
insert into AirportCode VALUES(null,'凯恩岛','YPR','CYPR','鲁珀特王子港机场','CANE ISLAND');
insert into AirportCode VALUES(null,'丘吉尔','YYQ','CYYQ','丘吉尔机场','CHURCHILL');
insert into AirportCode VALUES(null,'北湾','YYB','CYYB','北湾机场','NORTH BAY');
insert into AirportCode VALUES(null,'温莎','YQG','CYQG','温莎机场','WINDSOR');
insert into AirportCode VALUES(null,'基奇纳','YKF','','基奇纳机场','KITCHENER');
insert into AirportCode VALUES(null,'唐山','TVS','ZBSN','唐山三女河机场','TANGSHAN');
insert into AirportCode VALUES(null,'盖尔达耶','GHA','DAUG','盖尔达耶机场','GHARDAIA');
insert into AirportCode VALUES(null,'图古尔特','TGR','DAUK','图古尔特机场','TOUGGOURT');
insert into AirportCode VALUES(null,'瓦德','ELU','DAUO','盖马尔机场','-');
insert into AirportCode VALUES(null,'牧之原','FSZ','RJNS','静冈机场','MANGROVE');
insert into AirportCode VALUES(null,'大阪伊丹','ITM','RJOO','伊丹机场','OSAKA');
insert into AirportCode VALUES(null,'淮安','HIA','ZSSH','淮安涟水机场','HUAIAN');
insert into AirportCode VALUES(null,'巴厘巴板','BPN','WALL','巴厘巴板机场','BALIKPAPAN');
insert into AirportCode VALUES(null,'莱比锡','AOC','EDAC','莱比锡阿尔滕堡机场','LEIPZIG');
insert into AirportCode VALUES(null,'马德堡','CSO','EDBC','马德堡科赫施泰特机场','MAGDEBURG');
insert into AirportCode VALUES(null,'艾福特','ERF','EDDE','艾福特机场','ERFURT');
insert into AirportCode VALUES(null,'莱比锡','LEJ','EDDP','莱比锡哈勒机场','LEIPZIG');
insert into AirportCode VALUES(null,'萨尔布鲁根','SCN','EDDR','萨尔布吕肯机场','SAARBRUCKEN');
insert into AirportCode VALUES(null,'埃格尔斯巴赫','QEF','EDFE','埃格尔斯巴赫机场','EGELSBACH');
insert into AirportCode VALUES(null,'法兰克福','HHN','EDFH','法兰克福哈恩机场','FRANKFURT');
insert into AirportCode VALUES(null,'曼海姆','MHG','EDFM','曼海姆市机场','MANNHEIM');
insert into AirportCode VALUES(null,'布尔巴赫','SGE','EDGS','Siegerland机场','BURBACH');
insert into AirportCode VALUES(null,'汉堡','XFW','EDHI','Hamburg Finkenwerder机场','HAMBURG');
insert into AirportCode VALUES(null,'叙尔特岛','GWT','EDXW','叙尔特岛机场','SYLT');
insert into AirportCode VALUES(null,'奥勒松','AES','ENAL','奥勒松机场','ALESUND');
insert into AirportCode VALUES(null,'Rygge','RYG','ENRY','Rygge机场','RYGGE');
insert into AirportCode VALUES(null,'海于格松','HAU','ENHD','海于格松机场','HAUGESUND');
insert into AirportCode VALUES(null,'克里斯蒂安桑','KRS','ENCN','克里斯蒂安桑机场','KRISTIANSAND');
insert into AirportCode VALUES(null,'勒罗斯','RRS','ENRO','Roeros机场','ROROS');
insert into AirportCode VALUES(null,'卡普斯卡辛','YYU','CYYU','卡普斯卡辛机场','KAPUSKASING');
insert into AirportCode VALUES(null,'哈迪港','YZT','CYZT','波特哈迪机场','HARDY');
insert into AirportCode VALUES(null,'博乐','BPL','ZWBL','新疆博乐机场','BOLE');
insert into AirportCode VALUES(null,'法鲁','ZFA','CZFA','法鲁机场','FARO');
insert into AirportCode VALUES(null,'厄尔顿','YXR','CYXR','厄尔顿机场','EARLTON');
insert into AirportCode VALUES(null,'贝伦斯里弗','YBV','CYBV','贝伦斯河机场','BERENS RIVER');
insert into AirportCode VALUES(null,'切特温德','YCQ','CYCQ','切特温德机场','CHETWYND');
insert into AirportCode VALUES(null,'萨菲尔德','YSD','CYSD','萨菲尔德机场','SUFFIELD');
insert into AirportCode VALUES(null,'波拉图克','YPC','CYPC','波拉图克机场','PAULATUK');
insert into AirportCode VALUES(null,'卡尔维','CLY','CYSN','圣凯瑟琳机场','CALVER');
insert into AirportCode VALUES(null,'伊武吉维克','YIK','CYIK','伊武吉维克机场','IVUJIVIK');
insert into AirportCode VALUES(null,'里格利','YWY','CYWY','里格利机场','WRIGLEY');
insert into AirportCode VALUES(null,'谢弗维尔','YKL','CYKL','谢弗维尔机场','SCHEFFERVILLE');
insert into AirportCode VALUES(null,'切斯特菲尔德因莱特','YCS','CYCS','切斯特菲尔德因莱特机场','CHESTERFIELD INLET');
insert into AirportCode VALUES(null,'惠尔科夫','YXN','CYXN','惠尔科夫机场','WHALE COVE');
insert into AirportCode VALUES(null,'布苏安加','USU','RPVV','布苏安加机场','BUSUANGA');
insert into AirportCode VALUES(null,'Havre ST. Pierre','YGV','CYGV','Havre ST. Pierre机场','HAVRE ST. PIERRE');
insert into AirportCode VALUES(null,'纳塔什昆','YNA','CYNA','纳塔什昆机场','NATASHQUAN');
insert into AirportCode VALUES(null,'瑟佛罗里达基斯','YSP','CYSP','瑟佛罗里达基斯马拉松机场','THE FLORIDA KEYS');
insert into AirportCode VALUES(null,'约克顿','YQV','CYQV','约克顿机场','YORKTON');
insert into AirportCode VALUES(null,'利亚德堡','YJF','CYJF','利亚德堡机场','FORT LIARD');
insert into AirportCode VALUES(null,'挪威豪斯','YNE','CYNE','挪威豪斯机场','NORWAY HOUSE');
insert into AirportCode VALUES(null,'埃德森','YET','CYET','埃德森机场','EDSON');
insert into AirportCode VALUES(null,'桑德斯皮特','YZP','CYZP','桑德斯皮特机场','SANDSPIT');
insert into AirportCode VALUES(null,'Kimmirut','YLC','CYLC','今米鲁特机场','KIMMIRUT');
insert into AirportCode VALUES(null,'茨林','YZW','CYZW','茨林机场','TESLIN');
insert into AirportCode VALUES(null,'奈恩','YDP','CYDP','奈恩机场','NAIN');
insert into AirportCode VALUES(null,'大特劳特湖','YTL','CYTL','大特劳特湖机场','BIG TROUT');
insert into AirportCode VALUES(null,'波蒂奇拉普大草原','YPG','CYPG','波蒂奇拉普大草原机场','PORTAGE LA PRARIE');
insert into AirportCode VALUES(null,'穆瑟尼','YMO','CYMO','穆瑟尼机场','MOOSONEE');
insert into AirportCode VALUES(null,'克内尔','YQZ','CYQZ','克内尔机场','QUESNEL');
insert into AirportCode VALUES(null,'福特雷索卢申','YFR','CYFR','福特雷索卢申机场','FORT RESOLUTION');
insert into AirportCode VALUES(null,'马库维克','YMN','CYFT','马库维克机场','MAKKOVIK');
insert into AirportCode VALUES(null,'派内贝','YKG','CYAS','派内贝机场','KANGIRSUK');
insert into AirportCode VALUES(null,'坎贝尔','YBL','CYBL','坎贝尔河机场','CAMPBELL');
insert into AirportCode VALUES(null,'布兰登','YBR','CYBR','布兰登机场','BRANDON');
insert into AirportCode VALUES(null,'布朗萨布隆','YBX','CYBX','布朗萨布隆机场','BLANC SABLON');
insert into AirportCode VALUES(null,'剑桥湾','YCB','CYCB','剑桥湾机场','CAMBRIDGE BAY');
insert into AirportCode VALUES(null,'纳奈莫','YCD','CYCD','纳奈莫机场','NANAIMO');
insert into AirportCode VALUES(null,'库格卢克图克','YCO','CYCO','库格卢克图克机场','KUGLUKTUK');
insert into AirportCode VALUES(null,'克莱德','YCY','CYCY','克莱德河机场','CLYDE');
insert into AirportCode VALUES(null,'道森','YDA','CYDA','道森城市机场','DAWSON');
insert into AirportCode VALUES(null,'多芬','YDN','CYDN','多芬机场','DAUPHIN');
insert into AirportCode VALUES(null,'丘吉尔','ZUM','CZUM','丘吉尔瀑布机场','CHURCHILL');
insert into AirportCode VALUES(null,'斯图尔特','ZST','CZST','斯图尔特机场','STEWART');
insert into AirportCode VALUES(null,'平彻克里克','WPC','CZPC','平彻克里克机场','PINCHER CREEK');
insert into AirportCode VALUES(null,'马塞特','ZMT','CZMT','马塞特机场','MASSET');
insert into AirportCode VALUES(null,'Tasiujaq','YTQ','CYTQ','Tasiujaq机场','TASIUJAQ');
insert into AirportCode VALUES(null,'汤普森','YTH','CYTH','汤普森机场','THOMPSON');
insert into AirportCode VALUES(null,'莱斯布里奇','YQL','CYQL','莱斯布里奇郡立机场','LETHBRIDGE');
insert into AirportCode VALUES(null,'凯诺拉','YQK','CYQK','凯诺拉机场','KENORA');
insert into AirportCode VALUES(null,'雷普尔斯湾','YUT','CYUT','雷普尔斯湾机场','REPULSE BAY');
insert into AirportCode VALUES(null,'霍尔海滩','YUX','CYUX','霍尔海滩机场','HALL BEACH');
insert into AirportCode VALUES(null,'鲁安','YUY','CYUY','鲁安诺兰达机场','ROUYN');
insert into AirportCode VALUES(null,'威廉斯湖','YWL','CYWL','威廉斯湖机场','WILLIANS LAKE');
insert into AirportCode VALUES(null,'克兰布鲁克','YXC','CYXC','克兰布鲁克卡纳迪丁罗基斯机场','CRANBROOK');
insert into AirportCode VALUES(null,'梅迪辛哈特','YXH','CYXH','梅迪辛哈特机场','MEDICINE HAT');
insert into AirportCode VALUES(null,'福特圣约翰','YXJ','CYXJ','福特圣约翰机场','FORT ST.JOHN');
insert into AirportCode VALUES(null,'苏卢考特','YXL','CYXL','苏卢考特机场','SIOUX LOOKOUT');
insert into AirportCode VALUES(null,'德瑞司','YXT','CYXT','德瑞司机场','TERRACE');
insert into AirportCode VALUES(null,'安大略','YXU','CYXU','加拿大伦敦机场','ONTARIO');
insert into AirportCode VALUES(null,'安大略','YRL','CYRL','安大略红湖机场','ONTARIO');
insert into AirportCode VALUES(null,'艾伯特王子城','YPA','CYPA','艾伯特王子城机场','PRINCE ALBERT');
insert into AirportCode VALUES(null,'和平河','YPE','CYPE','和平河机场','PEACE RIVER');
insert into AirportCode VALUES(null,'皮克尔','YPL','CYPL','皮克尔机场','PICKLE');
insert into AirportCode VALUES(null,'彼得博勒','YPQ','CYPQ','彼得博勒机场','PETERBOROUGH');
insert into AirportCode VALUES(null,'鲍威尔河','YPW','CYPW','鲍威尔河机场','POWELL RIVER');
insert into AirportCode VALUES(null,'Povungnituk','YPX','CYPX','Povungnituk机场','POVUNGNITUK');
insert into AirportCode VALUES(null,'福特奇佩恩','YPY','CYPY','福特奇佩恩机场','FORT CHIPEWYAN');
insert into AirportCode VALUES(null,'怀特科特','YZU','CYZU','怀特科特机场','WHITECOURT');
insert into AirportCode VALUES(null,'瓦勒多','YVO','CYVO','瓦勒多机场','VAL D.OR');
insert into AirportCode VALUES(null,'冷湖','YOD','CYOD','冷湖空军基地机场','COLD LAKE');
insert into AirportCode VALUES(null,'卡蒂','YOA','CYOA','卡蒂机场','EKATI');
insert into AirportCode VALUES(null,'德赖登','YHD','CYHD','德赖登机场','DRYDEN');
insert into AirportCode VALUES(null,'霍普','YHE','CYHE','霍普机场','HOPE');
insert into AirportCode VALUES(null,'巴瑟斯特','ZBF','CZBF','加拿大巴瑟斯特机场','BATHURST');
insert into AirportCode VALUES(null,'科勒尔港','YZS','CYZS','科勒尔港机场','CORAL HARBOUR');
insert into AirportCode VALUES(null,'艾伯塔','YZH','CYZH','艾伯塔奴湖机场','ALBERTA');
insert into AirportCode VALUES(null,'耶洛奈夫','YZF','CYZF','耶洛奈夫机场','YELLOWKNIFE');
insert into AirportCode VALUES(null,'蒙若利','YYY','CYYY','蒙若利机场','MONT JOLI');
insert into AirportCode VALUES(null,'圣约翰斯','YYT','CYYT','圣约翰斯机场','ST JOHN.S');
insert into AirportCode VALUES(null,'塔克托亚图克','YUB','CYUB','塔克托亚图克机场','TUKTOYAKTUK');
insert into AirportCode VALUES(null,'蒂明斯','YTS','CYTS','蒂明斯机场','TIMMINS');
insert into AirportCode VALUES(null,'阿帕拉契科拉','AAF','KAAF','阿帕拉契科拉机场','APALACHICOLA');
insert into AirportCode VALUES(null,'阿伦敦','ABE','KABE','阿伦敦机场','LEHIGH VALLEY');
insert into AirportCode VALUES(null,'阿比林','ABI','KABI','阿比林机场','ABILENE');
insert into AirportCode VALUES(null,'伯纳利欧','ABQ','KABQ','阿尔伯克基机场','BERNALILLO');
insert into AirportCode VALUES(null,'布朗','ABR','KABR','美国阿伯丁机场','BROWN');
insert into AirportCode VALUES(null,'岱斯','ABZ','EGPD','阿伯丁机场','DYCE');
insert into AirportCode VALUES(null,'楠塔基特','ACK','KACK','楠塔基特机场','NANTUCKET');
insert into AirportCode VALUES(null,'瓦科','ACT','KACT','瓦科地区机场','WACO TEXAS');
insert into AirportCode VALUES(null,'加利福尼亚州','ACV','KACV','阿克塔机场','CALIFORNIA');
insert into AirportCode VALUES(null,'波姆那','ACY','KACY','大西洋城机场','BOMUNA');
insert into AirportCode VALUES(null,'塔兰特','AFW','KAFW','Fort Worth Alliance机场','TARRANT');
insert into AirportCode VALUES(null,'匹兹堡','AGC','KAGC','Allegheny County机场','PITTSBURGH PENNSYLVANIA');
insert into AirportCode VALUES(null,'乔治亚州','AGS','KAGS','Augusta Regional机场','GEORGIA');
insert into AirportCode VALUES(null,'纽约','ALB','KALB','奥尔巴尼机场','NEW YORK');
insert into AirportCode VALUES(null,'艾丽斯','ALI','KALI','艾丽斯机场','ALICE');
insert into AirportCode VALUES(null,'奥尔顿','ALN','KALN','奥尔顿机场','ALTON');
insert into AirportCode VALUES(null,'滑铁卢','ALO','KALO','滑铁卢地区机场','WATERLOO');
insert into AirportCode VALUES(null,'瓦拉瓦拉','ALW','KALW','瓦拉瓦拉机场','WALLA WALLA');
insert into AirportCode VALUES(null,'阿马里洛','AMA','KAMA','阿马里洛机场','AMARILLO TEXAS');
insert into AirportCode VALUES(null,'安妮斯顿','ANB','KANB','安妮斯顿梅特勒波利滕机场','ANNISTON');
insert into AirportCode VALUES(null,'安德森','AND','KAND','安德森机场','ANDERSON');
insert into AirportCode VALUES(null,'阿尔皮纳','APN','KAPN','阿尔皮纳机场','ALPENA MICHIGAN');
insert into AirportCode VALUES(null,'沃特敦','ART','KART','沃特敦机场','WATERTOWN');
insert into AirportCode VALUES(null,'沃特敦','ATY','KATY','沃特敦地区机场','WATERTOWN');
insert into AirportCode VALUES(null,'奥斯汀','AUS','KAUS','奥斯汀贝格斯特罗姆机场','AUSTIN TEXAS');
insert into AirportCode VALUES(null,'阿什维尔','AVL','KAVL','阿什维尔机场','ASHEVILLE');
insert into AirportCode VALUES(null,'Pittston Township','AVP','KAVP','威尔克斯-巴里机场','PITTSTON TOWNSHIP');
insert into AirportCode VALUES(null,'亚历山德里亚','AXN','KAXN','亚历山德里亚机场','ALEXANDRIA');
insert into AirportCode VALUES(null,'卡拉马祖','AZO','KAZO','卡拉马祖/巴特尔克里克机场','KALAMAZOO');
insert into AirportCode VALUES(null,'伍兹湖县','BDE','KBDE','巴德特BAUDETTE机场','LAKE OF THE WOODS COUNTY');
insert into AirportCode VALUES(null,'布里奇波特','BDR','KBDR','布里奇波特机场','BRIDGEPORT CONNECTICUT');
insert into AirportCode VALUES(null,'布拉德福德','BFD','KBFD','布拉德福德机场','BRADFORD');
insert into AirportCode VALUES(null,'西雅图','BFI','KBFI','波音场国王郡立机场','SEATTLE');
insert into AirportCode VALUES(null,'贝克斯菲尔德','BFL','KBFL','梅多斯场机场','BAKERSFIELD CALIFORNIA');
insert into AirportCode VALUES(null,'莫比尔','BFM','KBFM','Mobile Downtown机场','MOBILE');
insert into AirportCode VALUES(null,'缅因','BGM','KBGM','Greater Binghamton机场','MAINE');
insert into AirportCode VALUES(null,'班戈','BGR','KBGR','班戈机场','BANGOR');
insert into AirportCode VALUES(null,'伯明翰','BHM','KBHM','伯明翰舒特尔斯沃思机场','BIRMINGHAM');
insert into AirportCode VALUES(null,'比林斯','BIL','KBIL','比林斯机场','BILLINGS');
insert into AirportCode VALUES(null,'俾斯麦','BIS','KBIS','俾斯麦机场','BISMARCK NORTH DAKOTA');
insert into AirportCode VALUES(null,'杰弗科','BJC','KBJC','杰弗科机场','JEFFCO');
insert into AirportCode VALUES(null,'贝克县','BKE','KBKE','贝克机场','BAKER COUNTY');
insert into AirportCode VALUES(null,'克利夫兰','BKL','KBKL','克利夫兰伯克莱克夫兰特机场','CLEVELAND');
insert into AirportCode VALUES(null,'贝灵汉','BLI','KBLI','贝灵汉机场','BELLINGHAM WASHINGTON');
insert into AirportCode VALUES(null,'博伊西','BOI','KBOI','博伊西机场','BOISE IDAHO');
insert into AirportCode VALUES(null,'柏林顿','BTV','KBTV','柏林顿机场','BURLINGTON');
insert into AirportCode VALUES(null,'柏林顿','BRL','KBRL','伯灵顿机场','BURLINGTON');
insert into AirportCode VALUES(null,'布朗斯维尔','BRO','KBRO','布朗斯维尔南帕德雷岛机场','BROWNSVILLE TEXAS');
insert into AirportCode VALUES(null,'比尤特','BTM','KBTM','比尤特贝尔穆尼机场','BUTTE MONTANA');
insert into AirportCode VALUES(null,'卡尔霍恩','BTL','KBTL','WK凯洛格机场','CALHOUN');
insert into AirportCode VALUES(null,'埃塞克斯','BVY','KBVY','贝弗利机场','ESSEX COUNTY');
insert into AirportCode VALUES(null,'哥伦比亚','CAE','KCAE','哥伦比亚梅特勒波利滕机场','COLUMBIA');
insert into AirportCode VALUES(null,'斯塔克','CAK','KCAK','阿克伦坎顿机场','STARK');
insert into AirportCode VALUES(null,'锡达城','CDC','KCDC','锡达城机场','CEDAR CITY');
insert into AirportCode VALUES(null,'斯普林菲尔德','CEF','KCEF','韦斯托弗机场','SPRINGFIELD');
insert into AirportCode VALUES(null,'克雷斯特维','CEW','KCEW','鲍勃赛克斯机场','CRESTVIEW');
insert into AirportCode VALUES(null,'开普吉拉多','CGI','KCGI','开普吉拉多机场','CAPE GIRARDEAU');
insert into AirportCode VALUES(null,'查塔努加','CHA','KCHA','Lovell Field机场','CHATTANOOGA');
insert into AirportCode VALUES(null,'夏洛茨维尔','CHO','KCHO','夏洛茨维尔阿尔伯马尔机场','CHARLOTTESVILLE');
insert into AirportCode VALUES(null,'查尔斯顿','CHS','KCHS','查尔斯顿AFB机场','CHARLESTON');
insert into AirportCode VALUES(null,'锡达拉皮兹','CID','KCID','锡达拉皮兹机场','CEDAR RAPIDS IOWA');
insert into AirportCode VALUES(null,'密歇根','CIU','KCIU','奇普瓦郡立机场','MICHIGAN');
insert into AirportCode VALUES(null,'布里奇波特','CKB','KCKB','North Central West Virginia机场','BRIDGEPORT CONNECTICUT');
insert into AirportCode VALUES(null,'克利夫兰','CLE','KCLE','Cleveland Hopkins机场','CLEVELAND');
insert into AirportCode VALUES(null,'布拉索斯','CLL','KCLL','Easterwood Field机场','BRAZOS COUNTY');
insert into AirportCode VALUES(null,'安吉利斯港','CLM','KCLM','William R. Fairchild机场','PORT ANGELES');
insert into AirportCode VALUES(null,'夏洛特','CLT','KCLT','夏洛特/道格拉斯机场','CHARLOTTE');
insert into AirportCode VALUES(null,'弗雷德里克顿','YFC','CYFC','弗雷德里克顿机场','FREDERICTON');
insert into AirportCode VALUES(null,'米苏拉','MSO','KMSO','米苏拉机场','MISSOULA');
insert into AirportCode VALUES(null,'明尼阿波利斯','MSP','KMSP','明尼阿波利斯―圣保罗机场','MINNEAPOLIS');
insert into AirportCode VALUES(null,'马塞纳','MSS','KMSS','马塞纳机场','MASSENA');
insert into AirportCode VALUES(null,'新奥尔良','MSY','KMSY','新奥尔良机场','NEW ORLEANS LOUISIANA');
insert into AirportCode VALUES(null,'马里兰','MTN','KMTN','马丁州立机场','MARYLAND');
insert into AirportCode VALUES(null,'Moses Lake','MWH','KMWH','格兰特郡立机场','MOSES LAKE');
insert into AirportCode VALUES(null,'默特尔比奇','MYR','KMYR','默特尔比奇机场','MYRTLE BEACH');
insert into AirportCode VALUES(null,'茨城','IBR','RJAH','茨城机场','BARAKI');
insert into AirportCode VALUES(null,'奥尔德尼','ACI','EGJA','奥尔德尼机场','ALDERNEY');
insert into AirportCode VALUES(null,'格恩济','GCI','EGJB','格恩济机场','GUERNSEY');
insert into AirportCode VALUES(null,'泽西','JER','EGJJ','泽西机场','JERSEY');
insert into AirportCode VALUES(null,'肖勒姆','ESH','EGKA','肖勒姆由海机场','SHOREHAM');
insert into AirportCode VALUES(null,'格洛斯特','GLO','EGBJ','格洛斯特机场','GLOUCESTER');
insert into AirportCode VALUES(null,'坎贝尔镇','CAL','EGEC','坎贝尔镇机场','CAMPBELTOWN');
insert into AirportCode VALUES(null,'加的夫','CWL','EGFF','加的夫机场','CARDIFF');
insert into AirportCode VALUES(null,'布里斯托尔','BRS','EGGD','布里斯托尔机场','BRISTOL');
insert into AirportCode VALUES(null,'伦敦','LTN','EGGW','伦敦卢顿机场','LONDON');
insert into AirportCode VALUES(null,'菲尼克斯','DVT','KDVT','凤凰城鹿谷/菲尼克斯迪尔山谷机场','PHOENIX');
insert into AirportCode VALUES(null,'罗萨里奥','ROS','SAAR','罗萨里奥机场','ROSARIO');
insert into AirportCode VALUES(null,'加斯佩','YGP','CYGP','加斯佩机场','GASPE');
insert into AirportCode VALUES(null,'杰拉尔顿','YGQ','CYGQ','杰拉尔顿机场','GERALDTON');
insert into AirportCode VALUES(null,'麦迪兰群岛','YGR','CYGR','麦迪兰群岛机场','ILES DE LA MADELEINE');
insert into AirportCode VALUES(null,'伊格卢利克','YGT','CYGT','伊格卢利克机场','IGLOOLIK');
insert into AirportCode VALUES(null,'库朱阿拉普','YGW','CYGW','库朱阿拉普机场','KUUJJUARAPIK');
insert into AirportCode VALUES(null,'古拉木','YGX','CYGX','古拉木机场','GILLAM');
insert into AirportCode VALUES(null,'穆斯乔','YMJ','CYMJ','穆斯乔机场','MOOSE JAW');
insert into AirportCode VALUES(null,'祺布嘎莫','YMT','CYMT','祺布嘎莫机场','CHIBOUGAMAU');
insert into AirportCode VALUES(null,'埃德蒙顿','YXD','CYXD','埃德蒙顿市中心机场','EDMONTON');
insert into AirportCode VALUES(null,'南安普敦','SOU','EGHI','南安普敦机场','SOUTHAMPTON');
insert into AirportCode VALUES(null,'伦敦','STN','EGSS','伦敦斯坦斯特德机场','LONDON');
insert into AirportCode VALUES(null,'蒙彼利埃','MPL','LFMT','蒙彼利埃地中海机场','MONTPELLIER');
insert into AirportCode VALUES(null,'第比利斯','TBS','UGTB','第比利斯机场','TBILISI');
insert into AirportCode VALUES(null,'埃尔果累阿','ELG','DAUE','埃尔果累阿机场','ALGERIA');
insert into AirportCode VALUES(null,'哈西迈萨乌德','HME','DAUH','哈西迈萨乌德机场','HASSI MESSAOUD');
insert into AirportCode VALUES(null,'因萨拉赫','INZ','DAUI','因萨拉赫机场','IN SALAH');
insert into AirportCode VALUES(null,'艾格瓦特','LOO','DAUL','艾格瓦特机场','LAGHOUAT');
insert into AirportCode VALUES(null,'提米蒙','TMX','DAUT','提米蒙机场','TIMIMOUN');
insert into AirportCode VALUES(null,'科托努','COO','DBBB','科托努机场','COTONOU');
insert into AirportCode VALUES(null,'瓦加杜古','OUA','DFFD','瓦加杜古机场','OUAGADOUGOU');
insert into AirportCode VALUES(null,'博博迪乌拉索','BOY','DFOO','BOBO DIOULASSO机场','BOBO DIOULASSO');
insert into AirportCode VALUES(null,'库马西','KMS','DGSI','库马西机场','KUMASI');
insert into AirportCode VALUES(null,'阿布贾','ABV','DNAA','阿布贾机场','ABUJA');
insert into AirportCode VALUES(null,'泰贝萨','TEE','DABS','泰贝萨机场','TEBESSA');
insert into AirportCode VALUES(null,'康斯坦丁','CZL','DABC','CONSTANTINE MOHAMED BOUDIAF机场','CONSTANTINE');
insert into AirportCode VALUES(null,'安纳巴','AAE','DABB','安纳巴机场','ANNABA');
insert into AirportCode VALUES(null,'因阿迈纳斯','IAM','DAUZ','因阿迈纳斯机场','IN AMENAS');
insert into AirportCode VALUES(null,'扎里亚','ZAR','DNZA','扎里亚机场','ZARIA');
insert into AirportCode VALUES(null,'马拉迪','MFQ','DRRM','马拉迪机场','MARADI');
insert into AirportCode VALUES(null,'尼亚美','NIM','DRRN','尼亚美机场','NIAMEY');
insert into AirportCode VALUES(null,'阿加德兹','AJY','DRZA','阿加德兹机场','AGADES');
insert into AirportCode VALUES(null,'津德尔','ZND','DRZR','津德尔机场','ZINDER');
insert into AirportCode VALUES(null,'塔巴卡','TBJ','DTKA','塔巴卡机场','TABARKA');
insert into AirportCode VALUES(null,'莫纳斯提尔','MIR','DTMB','莫纳斯提尔机场','MONASTIR');
insert into AirportCode VALUES(null,'加夫萨','GAF','DTTF','加夫萨机场','GAFSA');
insert into AirportCode VALUES(null,'加贝斯','GAE','DTTG','加贝斯机场','GABES');
insert into AirportCode VALUES(null,'杰尔巴','DJE','DTTJ','梅利塔机场','DJERBA');
insert into AirportCode VALUES(null,'斯法克斯','SFA','DTTX','斯法克斯Thyna机场','SFAX');
insert into AirportCode VALUES(null,'托泽尔','TOE','DTTZ','托泽尔机场','TOZEUR');
insert into AirportCode VALUES(null,'安特卫普','ANR','EBAW','安特卫普机场','ANRWERP');
insert into AirportCode VALUES(null,'奥斯坦德','OST','EBOS','奥斯坦德机场','OSTEND');
insert into AirportCode VALUES(null,'赫林斯多夫','HDF','EDAH','赫林斯多夫机场','HERINGSDORF');
insert into AirportCode VALUES(null,'蒙斯特','FMO','EDDG','蒙斯特机场','MUENSTER');
insert into AirportCode VALUES(null,'基尔','KEL','EDHK','基尔机场','KIEL');
insert into AirportCode VALUES(null,'乌兰乌德','UUD','UIUU','乌兰乌德机场','ULAN-UDE');
insert into AirportCode VALUES(null,'阿尔汉格尔斯克','ARH','ULAA','阿尔汉格尔斯克机场','ARKHANGELSK');
insert into AirportCode VALUES(null,'AMDERMA','AMV','ULDD','AMDERMA机场','AMDERMA');
insert into AirportCode VALUES(null,'摩尔曼斯科','MMK','ULMM','摩尔曼斯科机场','MURMANSK');
insert into AirportCode VALUES(null,'瓜拉丁加奴','TGG','WMKN','瓜拉丁加奴机场','KUALA TERENGGANU');
insert into AirportCode VALUES(null,'奥兰','ORN','DAOO','艾塞尼亚机场','ORAN');
insert into AirportCode VALUES(null,'特莱姆森','TLM','DAON','特莱姆森机场','TLEMCEN');
insert into AirportCode VALUES(null,'廷杜夫','TIN','DAOF','廷杜夫机场','TINDOUF');
insert into AirportCode VALUES(null,'提亚雷特','TID','DAOB','提亚雷特机场','TIARET');
insert into AirportCode VALUES(null,'因盖扎姆','INF','DATG','因盖扎姆机场','IN GUEZZAM');
insert into AirportCode VALUES(null,'安托法加斯塔','ANF','SCFA','CERRO MORENO机场','ANTOFAGASTA');
insert into AirportCode VALUES(null,'洛斯安赫莱斯','LSQ','SCGE','洛斯安赫莱斯机场','LOS ANGELES');
insert into AirportCode VALUES(null,'沙普洛','YLD','CYLD','沙普洛机场','CHAPLEAU');
insert into AirportCode VALUES(null,'梅多莱克','YLJ','CYLJ','梅多莱克机场','MEADOW LAKE');
insert into AirportCode VALUES(null,'劳埃德明斯特','YLL','CYLL','劳埃德明斯特机场','LLOYDMINSTER');
insert into AirportCode VALUES(null,'艾乐特','YLT','CYLT','艾乐特机场','ALERT');
insert into AirportCode VALUES(null,'坎吉克斯瓦尔','XGR','CYLU','坎吉克斯瓦尔机场','KANGIQSUALUJJUAQ');
insert into AirportCode VALUES(null,'马克马里堡','YMM','CYMM','马克马里堡机场','FORT MCMURRAY');
insert into AirportCode VALUES(null,'乌苗奥','YUD','CYMU','乌苗奥机场','UMIUJAG');
insert into AirportCode VALUES(null,'蒙特利尔','YMX','CYMX','米拉贝尔机场','MONTREAL');
insert into AirportCode VALUES(null,'韦明吉','YNC','CYNC','韦明吉机场','WEMINDJI');
insert into AirportCode VALUES(null,'加蒂诺','YND','CYND','加蒂诺机场','GATINEAU');
insert into AirportCode VALUES(null,'格林伍德','YZX','CYZX','格林伍德机场','GREENWOOD');
insert into AirportCode VALUES(null,'七岛港','YZV','CYZV','七岛港机场','SEPT-ILES');
insert into AirportCode VALUES(null,'古斯贝','YYR','CYYR','古斯贝机场','GOOSE BAY');
insert into AirportCode VALUES(null,'斯威夫特卡伦特','YYN','CYYN','斯威夫特卡伦特机场','SWIFT CURRENT');
insert into AirportCode VALUES(null,'TALOYOAK','YYH','CYYH','TALOYOAK机场','TALOYOAK');
insert into AirportCode VALUES(null,'夏洛特城','YYG','CYYG','夏洛特城机场','CHARLOTTETOWN');
insert into AirportCode VALUES(null,'彭蒂科顿','YYF','CYYF','彭蒂科顿机场','PENTICTON');
insert into AirportCode VALUES(null,'纳尔逊堡','YYE','CYYE','纳尔逊堡机场','FORT NELSON');
insert into AirportCode VALUES(null,'史密瑟斯','YYD','CYYD','史密瑟斯机场','SMITHERS');
insert into AirportCode VALUES(null,'卡尔加里','YYC','CYYC','CALGARY机场','CALGARY');
insert into AirportCode VALUES(null,'沃瓦','YXZ','CYXZ','沃瓦机场','WAWA');
insert into AirportCode VALUES(null,'阿伯兹福德','YXX','CYXX','阿伯兹福德机场','ABBOTSFORD');
insert into AirportCode VALUES(null,'卑尔根','BGO','ENBR','卑尔根机场','BERGEN');
insert into AirportCode VALUES(null,'克拉斯诺亚尔斯克','KJA','UNKL','克拉斯诺亚尔斯克机场','KRASNOYARSK KRAI');
insert into AirportCode VALUES(null,'坎佩切','CPE','MMCP','坎佩切机场','CAMPECHE');
insert into AirportCode VALUES(null,'华雷斯','CJS','MMCS','华雷斯机场','CIUDAD JUAREZ');
insert into AirportCode VALUES(null,'奇琴伊查','CZA','MMCT','奇琴伊查机场','CHICHEN ITZA');
insert into AirportCode VALUES(null,'奇瓦瓦','CUU','MMCU','奇瓦瓦机场','CHIHUAHUA');
insert into AirportCode VALUES(null,'维多利亚城','CVM','MMCV','维多利亚城机场','CIUDAD VICTORIA');
insert into AirportCode VALUES(null,'克拉克','CRK','RPLC','克拉克机场','MANILA');
insert into AirportCode VALUES(null,'普拉塔港','POP','MDPP','Puerto PLata Gregorio Luperon机场','PUERTO PLATA');
insert into AirportCode VALUES(null,'圣多明各','SDQ','MDSD','LAS AMERICAS机场','SANTO DOMINGO');
insert into AirportCode VALUES(null,'圣地亚哥','STI','MDST','SANTIAGO MUNICIPAL机场','SANTIAGO');
insert into AirportCode VALUES(null,'阿卡普尔科','ACA','MMAA','阿卡普尔科机场','ACAPULCO');
insert into AirportCode VALUES(null,'蒙特哥贝','MBJ','MKJS','SANGSTER机场','MONTEGO BAY');
insert into AirportCode VALUES(null,'蒙特雷','MTY','MMMY','墨西哥蒙特雷机场','MONTERREY');
insert into AirportCode VALUES(null,'阿瓜斯卡连特斯','AGU','MMAS','阿瓜斯卡连特斯机场','AGUASCALIENTES');
insert into AirportCode VALUES(null,'HUATULCO','HUX','MMBT','HUATULCO机场','HUATULCO');
insert into AirportCode VALUES(null,'魁那伐克','CVJ','MMCB','魁那伐克机场','CUERNAVACA');
insert into AirportCode VALUES(null,'卡门城','CME','MMCE','卡门城机场','CIUDAD DEL CARMEN');
insert into AirportCode VALUES(null,'切图马尔','CTM','MMCM','切图马尔机场','CHETUMAL');
insert into AirportCode VALUES(null,'科苏梅尔','CZM','MMCZ','科苏梅尔机场','COZUMEL');
insert into AirportCode VALUES(null,'科利马','CLQ','MMIA','科利马机场','COLIMA');
insert into AirportCode VALUES(null,'冲绳','ISG','ROIG','石垣机场','OKINAWA');
insert into AirportCode VALUES(null,'巴拉奥纳','BRX','MDBH','巴拉奥纳机场','BARAHONA');
insert into AirportCode VALUES(null,'隆德里纳','LDB','SBLO','隆德里纳机场','LONDRINA');
insert into AirportCode VALUES(null,'马恩河畔沙隆','XCR','LFOK','瓦特里机场','CHALONS SUR MARNE');
insert into AirportCode VALUES(null,'佐贺','HSG','RJFS','佐贺机场','ZUOHE');
insert into AirportCode VALUES(null,'埃弗里特','PAE','KPAE','埃弗雷特潘恩机场','EVERETT');
insert into AirportCode VALUES(null,'恩德培','EBB','HUEN','恩德培机场','ENTEBBE');
insert into AirportCode VALUES(null,'彼得罗巴甫洛夫斯克','PKC','UHPP','彼得罗巴甫洛夫斯克机场','PETROPAVLOVSK-KAMCHATSKY');
insert into AirportCode VALUES(null,'热那亚','GOA','LIMJ','热那亚―西塞斯特里克里斯托弗?哥伦布机场','JANUA');
insert into AirportCode VALUES(null,'阿斯塔纳','TSE','UACC','阿斯塔纳机场','ASTANA');
insert into AirportCode VALUES(null,'卡拉干达','KGF','UAKK','卡拉干达机场','KARAGANDA');
insert into AirportCode VALUES(null,'佩韦克','PWE','UHMP','佩韦克机场','PEVEK');
insert into AirportCode VALUES(null,'南萨哈林斯克','UUS','UHSS','南萨哈林斯克机场','YUZHNO-SAKHALINSK');
insert into AirportCode VALUES(null,'普斯科夫','PKV','ULOO','普斯科夫机场','PSKOV');
insert into AirportCode VALUES(null,'沃洛格达','VGD','ULWW','沃洛格达机场','VOLOGDA');
insert into AirportCode VALUES(null,'布雷斯特','BQT','UMBB','布雷斯特机场','BREST');
insert into AirportCode VALUES(null,'戈梅尔','GME','UMGG','戈梅尔机场','GOMEL');
insert into AirportCode VALUES(null,'维捷布斯克','VTB','UMII','维捷布斯克机场','VITEBSK');
insert into AirportCode VALUES(null,'加里宁格勒','KGD','UMKK','加里宁格勒机场','KALININGRAD');
insert into AirportCode VALUES(null,'格罗德诺','GNA','UMMG','格罗德诺机场','GRODNO');
insert into AirportCode VALUES(null,'巴库','GYD','UBBB','巴库比纳机场','BAKU');
insert into AirportCode VALUES(null,'别尔哥罗德','EGO','UUOB','别尔哥罗德机场','BELGOROD');
insert into AirportCode VALUES(null,'沃罗涅什','VOZ','UUOO','沃罗涅什机场','VORONEZH');
insert into AirportCode VALUES(null,'乌赫塔','UCT','UUYH','乌赫塔机场','UKHTA');
insert into AirportCode VALUES(null,'乌辛斯克','USK','UUYS','乌辛斯克机场','USINSK');
insert into AirportCode VALUES(null,'沃尔库塔','VKT','UUYW','沃尔库塔机场','VORKUTA');
insert into AirportCode VALUES(null,'下诺夫哥罗德','GOJ','UWGG','下诺夫哥罗德机场','NIZHNIY NOVGOROD');
insert into AirportCode VALUES(null,'蒂华纳','TIJ','MMTJ','蒂华纳-罗德里格斯机场','TIJUANA');
insert into AirportCode VALUES(null,'特罗纳','TRH','UOTT','特罗纳机场','TRONA');
insert into AirportCode VALUES(null,'华欣','HHQ','VTPH','华欣机场','HUA HIN');
insert into AirportCode VALUES(null,'纽卡斯尔','NTL','YWLM','威廉斯敦机场','NEWCASTLE');
insert into AirportCode VALUES(null,'埃德蒙顿','YEG','CYEG','埃德蒙顿机场','EDMONTON');
insert into AirportCode VALUES(null,'诺福克岛','NLK','YSNF','诺福克岛机场','NORFOLK ISLAND');
insert into AirportCode VALUES(null,'达博','DBO','YSDU','达博机场','DUBBO');
insert into AirportCode VALUES(null,'圣诞岛','XCH','YPXM','圣诞岛机场','CHRISTMAS ISLAND');
insert into AirportCode VALUES(null,'伍默拉','UMR','YPWR','伍默拉机场','WOOMERA');
insert into AirportCode VALUES(null,'凯瑟琳','KTR','YPTN','廷德尔机场','KATHERINE');
insert into AirportCode VALUES(null,'黑德兰港','PHE','YPPD','黑德兰港机场','PORT HEDLAND');
insert into AirportCode VALUES(null,'利尔蒙斯','LEA','YPLM','利尔蒙斯机场','LEARMONTH');
insert into AirportCode VALUES(null,'库努纳拉','KNX','YPKU','库努纳拉机场','KUNUNURRA');
insert into AirportCode VALUES(null,'卡尔古利','KGI','YPKG','卡尔古利机场','KALGOORLIE');
insert into AirportCode VALUES(null,'詹达科特','JAD','YPJT','詹达科特机场','JANDAKOT');
insert into AirportCode VALUES(null,'柔佛州','JHB','WMKJ','士乃机场','JOHOR');
insert into AirportCode VALUES(null,'戈夫','GOV','YPGV','戈夫机场','GOVE');
insert into AirportCode VALUES(null,'科科斯岛','CCK','YPCC','科科斯岛机场','COCOS ISLANDS');
insert into AirportCode VALUES(null,'朗塞斯顿','LST','YMLT','朗塞斯顿机场','LAUNCESTON');
insert into AirportCode VALUES(null,'霍巴特','HBA','YMHB','霍巴特机场','HOBART');
insert into AirportCode VALUES(null,'霍恩岛','HID','YHID','霍恩岛机场','HORN ISLAND');
insert into AirportCode VALUES(null,'杰拉尔顿','GET','YGEL','杰拉尔敦机场','GERALDTON');
insert into AirportCode VALUES(null,'班顿杜','FDU','FZBO','班顿杜机场','BANDUNDU');
insert into AirportCode VALUES(null,'海霍','HEH','VYHH','茵莱湖机场','HEHO');
insert into AirportCode VALUES(null,'良乌','NYU','VYNU','良乌机场','NYAUNG-U');
insert into AirportCode VALUES(null,'布哈拉','BHK','UTSB','布哈拉机场','BUKHARA');
insert into AirportCode VALUES(null,'布鲁姆','BME','YBRM','布鲁姆机场','BROOME');
insert into AirportCode VALUES(null,'罗克汉普顿','ROK','YBRK','罗克汉普顿机场','ROCKHAMPTON');
insert into AirportCode VALUES(null,'伦敦','LCY','EGLC','伦敦城市机场','LONDON');
insert into AirportCode VALUES(null,'金沙萨','FIH','FZAA','金沙萨恩吉利机场','KINSHASA');
insert into AirportCode VALUES(null,'卢本巴希','FBM','FZQA','卢本巴希机场','LUBUMBASHI');
insert into AirportCode VALUES(null,'卡萨布兰卡','CMN','GMMN','默罕默德V机场','CASABLANCA');
insert into AirportCode VALUES(null,'阿什哈巴德','ASB','UTAA','阿什哈巴德机场','ASHGABAT');
insert into AirportCode VALUES(null,'黔江','JIQ','ZUQJ','黔江舟白机场','ZHOUBAI');
insert into AirportCode VALUES(null,'承德','CEH','','承德机场','CHENGDE');
insert into AirportCode VALUES(null,'塔拉哈西','TLH','KTLH','塔拉哈西机场','TALLAHASSEE');
insert into AirportCode VALUES(null,'杜尚别','DYU','UTDD','杜尚别机场','DUSHANBE');
insert into AirportCode VALUES(null,'叶卡捷琳堡','SVX','USSS','叶卡捷琳堡/科利佐沃机场机场','YEKATERINBURG');
insert into AirportCode VALUES(null,'海德拉巴','HYD','VOHY','海德拉巴机场','HYDERABAD');
insert into AirportCode VALUES(null,'伊兹密尔','ADB','LTBJ','伊兹密尔Adnan Menderes机场','IZMIR');
insert into AirportCode VALUES(null,'基辅','KBP','UKBB','波里斯珀尔机场','KIEV');
insert into AirportCode VALUES(null,'雅加达','JKT','','雅加达机场','JAKARTA');
insert into AirportCode VALUES(null,'莫雷利亚','MLM','MMMM','莫雷利亚机场','MORELIA');
insert into AirportCode VALUES(null,'维多利亚','SEZ','FSIA','塞舌尔机场','VICTORIA');
insert into AirportCode VALUES(null,'纽约','LGA','KLGA','拉瓜迪亚机场','NEW YORK');
insert into AirportCode VALUES(null,'克林顿县','CWI','','克林顿机场','CLINTON IOWA');
insert into AirportCode VALUES(null,'岘港','DAD','VVDN','岘港机场','DA NANG');
insert into AirportCode VALUES(null,'马塔兰','AMI','WADA','Selaparang机场','MATARAM');
insert into AirportCode VALUES(null,'利斯莫尔','LSY','YLIS','利斯莫尔机场','LISMORE');
insert into AirportCode VALUES(null,'阿尔山','YIE','ZBES','阿尔山伊尔施机场','ARXAN');
insert into AirportCode VALUES(null,'托卢','TLU','SKTL','托卢机场','TOLU');
insert into AirportCode VALUES(null,'富山','TOY','RJNT','富山机场','FUSHAN');
insert into AirportCode VALUES(null,'楠普拉','APL','FQNP','楠普拉机场','NAMPULA');
insert into AirportCode VALUES(null,'巴东','PDG','WIPT','达滨机场','PADANG');
insert into AirportCode VALUES(null,'日喀则','RKZ','ZURK','日喀则和平机场','RIKAZE');
insert into AirportCode VALUES(null,'德班','DUR','FADN','德班机场','DURBAN');
insert into AirportCode VALUES(null,'布雷西亚','VBS','LIPO','Brescia Montichiari机场','BRESCIA');
insert into AirportCode VALUES(null,'利伯维尔','LBV','FOOL','利伯维尔莱昂姆巴机场','LIBREVILIE');
insert into AirportCode VALUES(null,'内罗毕','NBO','HKJK','内罗毕乔莫?肯雅塔机场','NAIROBI');
insert into AirportCode VALUES(null,'米兰','LIN','LIML','米兰利纳特机场','MILAN');
insert into AirportCode VALUES(null,'拉纳卡','LCA','LCLK','拉纳卡机场','LARNACA');
insert into AirportCode VALUES(null,'林肯','LNK','KLNK','林肯机场','LINCOLN');
insert into AirportCode VALUES(null,'达累斯萨拉姆','DAR','HTDA','尼雷尔机场','DAR ES SALAAM');
insert into AirportCode VALUES(null,'底特律','DTW','KDTW','底特律都会韦恩县机场','DETROIT');
insert into AirportCode VALUES(null,'哈拉雷','HRE','FVHA','哈拉雷机场','HARARE');
insert into AirportCode VALUES(null,'拉巴斯','LPB','SLLP','EL ALTO机场','LA PAZ');
insert into AirportCode VALUES(null,'圣何塞','SJO','MROC','胡安 圣玛利亚机场','SAN JOSE');
insert into AirportCode VALUES(null,'圣何塞','SJC','KSJC','诺曼?米内塔圣何塞机场','SAN JOSE');
insert into AirportCode VALUES(null,'圣萨尔瓦多','SAL','MSLP','圣萨尔瓦多 科马拉帕机场','SAN SALVADOR');
insert into AirportCode VALUES(null,'费耶特维尔','FYV','KFAY','费耶特维尔机场','FAYETTEVILLE, ARKANSAS');
insert into AirportCode VALUES(null,'奥兰多','ORL','','赫登机场','AOKELAN');
insert into AirportCode VALUES(null,'冈山','OKJ','RJOB','冈山机场','OKAYAMA PREFECTURE');
insert into AirportCode VALUES(null,'南迪','NAN','NFFN','南迪机场','NADI');
insert into AirportCode VALUES(null,'伊瓜苏','IGR','SARI','伊瓜苏机场','IGUAZU');
insert into AirportCode VALUES(null,'纽约','ISP','KISP','长岛机场','NEW YORK');
insert into AirportCode VALUES(null,'哈特福德县','BDL','KBDL','哈特福德机场','HARTFORD COUNTY, CONNECTICUT');
insert into AirportCode VALUES(null,'内尔斯普雷特','MQP','FAKN','克鲁格姆普马兰加国际机场机场','NELSPRUIT');
insert into AirportCode VALUES(null,'斯普利特','SPU','LDSP','斯普利特机场机场','SPLIT');
insert into AirportCode VALUES(null,'韦恩堡','FWA','KFWA','韦恩堡巴尔机场','FORTWAYNE');
insert into AirportCode VALUES(null,'金昌','JIC','ZLJC','金昌机场','JINCHANG');
insert into AirportCode VALUES(null,'拉瓦格','LAO','','拉瓦格机场','LAOAG');
insert into AirportCode VALUES(null,'莫尔兹比港','POM','AYPY','莫尔兹比港机场','PORT MORESBY');
insert into AirportCode VALUES(null,'华盛顿','IAD','KIAD','华盛顿杜勒斯机场','WASHINGTON');
insert into AirportCode VALUES(null,'卡利亚里','CAG','LIEE','卡利亚里机场','CAGLIARI');
insert into AirportCode VALUES(null,'罗马','CIA','LIRA','罗马钱皮诺机场','ROME');
insert into AirportCode VALUES(null,'帕罗','PBH','VQPR','帕罗机场','PARO');
insert into AirportCode VALUES(null,'维尔纽斯','VNO','EYVI','维尔纽斯机场','VILNIUS');
insert into AirportCode VALUES(null,'太子港国际','PAP','MTPP','太子港国际机场','PORT-AU-PRINCE');
insert into AirportCode VALUES(null,'兰卡威','LGK','WMKL','浮罗交怡机场','LANGKAWI');
insert into AirportCode VALUES(null,'马耳他','MLA','LMML','马耳他机场','MALTA');
insert into AirportCode VALUES(null,'卡利博','KLO','RPVK','卡利博机场','KALIBO');
insert into AirportCode VALUES(null,'张掖','YZY','ZLZY','张掖机场','ZHANGYE');
insert into AirportCode VALUES(null,'斗湖','TWU','WBKW','斗湖机场','TAWAU');
insert into AirportCode VALUES(null,'黎牙实比','LGP','','黎牙实比机场','LEGASPI');
insert into AirportCode VALUES(null,'塔比拉兰','TAG','','塔比拉兰机场','TAGBILARAN');
insert into AirportCode VALUES(null,'阿洛岛','ARD','','阿洛岛机场','ALOR ISLAND');
insert into AirportCode VALUES(null,'古邦','KOE','','古邦机场','KUPANG');
insert into AirportCode VALUES(null,'卢萨卡','LUN','FLLS','卢萨卡机场','LUSAKA');
insert into AirportCode VALUES(null,'皇后镇','ZQN','NZQN','皇后镇机场','QUEENSTOWN');
insert into AirportCode VALUES(null,'扬州','YTY','ZSYA','扬州泰州机场','YANGZHOU');
insert into AirportCode VALUES(null,'巴彦淖尔','RLK','ZBYZ','巴彦淖尔天吉泰机场','BAYAN NUR');
insert into AirportCode VALUES(null,'特罗姆瑟','TOS','','特罗姆瑟机场','TROMSO');
insert into AirportCode VALUES(null,'朗勃拉邦','LPQ','','朗勃拉邦机场','LUANG PRABANG');
insert into AirportCode VALUES(null,'小松','KMQ','RJNK','小松机场','KOMATSU');
insert into AirportCode VALUES(null,'布加勒斯特','OTP','LROP','布加勒斯特奥托佩尼机场','BUCHAREST');
insert into AirportCode VALUES(null,'库里蒂巴','CWB','SBCT','库里蒂巴机场','CURITIBA');
insert into AirportCode VALUES(null,'普罗维登斯','PVD','KPVD','普罗维登斯机场','PROVIDENCE');
insert into AirportCode VALUES(null,'马普托','MPM','FQMA','马普托机场','MAPUTO');
insert into AirportCode VALUES(null,'哈瓦那','HAV','','哈瓦那何塞马蒂机场','HAVANA');
insert into AirportCode VALUES(null,'毛里求斯','MRU','FIMP','毛里求斯机场','MAURITIUS');
insert into AirportCode VALUES(null,'菲尼克斯','PHX','KPHX','菲尼克斯天港机场','PHOENIX');
insert into AirportCode VALUES(null,'维罗纳','VRN','','维罗纳机场','VERONA');
insert into AirportCode VALUES(null,'关岛','GUM','PGUM','关岛机场','GUAM');
insert into AirportCode VALUES(null,'胡占德','LBD','UTDL','胡占德机场','KHUDZHAND');
insert into AirportCode VALUES(null,'胡占德','LBD','UTDL','胡占德机场','KHUDZHAND');
insert into AirportCode VALUES(null,'里加','RIX','EVRA','里加机场','RIGA');
insert into AirportCode VALUES(null,'布拉戈维申斯克','BQS','UHBB','布拉戈维申斯克机场','BLAGOVESCHENSK');
insert into AirportCode VALUES(null,'雅库茨克','YKS','','雅库茨克机场','YAKUTSK');
insert into AirportCode VALUES(null,'奥伦堡','REN','UWOO','奥伦堡机场','ORENBURG');
insert into AirportCode VALUES(null,'巴林','BAH','OBBI','巴林机场','MOURINHO HA LA');
insert into AirportCode VALUES(null,'诺维奇','NWI','EGSH','诺维奇机场','NORWICH');
insert into AirportCode VALUES(null,'布雷加港','LMQ','HLMB','布雷加港机场','MARSA EL BREGA');
insert into AirportCode VALUES(null,'弗里敦','FNA','','弗里敦机场','FREETOWN');
insert into AirportCode VALUES(null,'巴士拉','BSR','ORMM','巴士拉机场','BASRA');
insert into AirportCode VALUES(null,'关丹','KUA','WMKD','关丹机场','KUANTAN');
insert into AirportCode VALUES(null,'里奥格兰德','RGA','SAWE','里奥格兰德机场','RIO GRANDE');
insert into AirportCode VALUES(null,'清莱','CEI','VTCT','清莱机场','CHIANAG RAI');
insert into AirportCode VALUES(null,'普林塞萨港','PPS','RPVP','普林塞萨港机场','PUERTO PRINCESA');
insert into AirportCode VALUES(null,'万纶','URT','','万纶机场','SURAT THANI');
insert into AirportCode VALUES(null,'毕尔巴鄂','BIO','LEBB','毕尔巴鄂机场','BILBAO');
insert into AirportCode VALUES(null,'比亚里茨','BIQ','LFBZ','比亚里茨-安格雷机场','BIARRITZ');
insert into AirportCode VALUES(null,'科钦','COK','VOCI','科钦机场','KOCHI');
insert into AirportCode VALUES(null,'柏林','BER','EDDB','柏林勃兰登堡机场','BERLIN');
insert into AirportCode VALUES(null,'温得和克','WDH','FYWH','温得和克卢格哈威机场','WINDHOEK');
insert into AirportCode VALUES(null,'台东','TTT','RCFN','台东丰年机场','TAIDONG');
insert into AirportCode VALUES(null,'布拉柴维尔','BZV','FCBB','布拉柴维尔马亚机场','BRAZZAVILLE');
insert into AirportCode VALUES(null,'马斯喀特','MCT','OOMS','马斯喀特机场','MUSCAT');
insert into AirportCode VALUES(null,'巴马科','BAM','GABS','巴马科机场','BAMAKO');
insert into AirportCode VALUES(null,'三宝垄','SRG','WARS','三宝垄艾哈迈德亚尼机场','SEMARANG');
insert into AirportCode VALUES(null,'斯德哥尔摩','NYO','','斯德哥尔摩史卡夫斯塔机场','STOCKHOLM');
insert into AirportCode VALUES(null,'辛辛那提','CVG','KCVG','辛辛那提机场','CINCINNATI');
insert into AirportCode VALUES(null,'巴淡岛','BTH','WIKB','巴淡岛机场','BATAM');
insert into AirportCode VALUES(null,'Tucson','TUS','KTUS','图森机场','TUCSON');
insert into AirportCode VALUES(null,'马略卡岛帕尔马','PMI','LEPA','马略卡岛帕尔马机场','PALMA DE MALLORCA');
insert into AirportCode VALUES(null,'匹兹堡','PIT','KPIT','匹兹堡机场','PITTSBURGH PENNSYLVANIA');
insert into AirportCode VALUES(null,'科纳','KOA','PHKO','科纳机场','KONA');
insert into AirportCode VALUES(null,'圣塔安那','SNA','','圣塔安那橙郡县机场','SANTA ANA');
insert into AirportCode VALUES(null,'卡胡卢伊','OGG','','卡胡卢伊机场','KAHULUI');
insert into AirportCode VALUES(null,'甲米','KBV','VTSG','甲米机场','KRABI');
insert into AirportCode VALUES(null,'青森','AOJ','RJSA','青森机场','AOMORI');
insert into AirportCode VALUES(null,'基多','UIO','SEQU','基多机场','QUITO');
insert into AirportCode VALUES(null,'麦迪逊','MSN','KMSN','麦迪逊机场','MADISON');
insert into AirportCode VALUES(null,'圣芭芭拉','SBA','KSBA','圣芭芭拉机场','SANTA BARBARA');
insert into AirportCode VALUES(null,'Springfield-Branson National','SGF','KSG','斯普林菲尔德机场','SPRINGFIELD');
insert into AirportCode VALUES(null,'Springfield-Branson National','SGF','KSG','斯普林菲尔德机场','SPRINGFIELD');
insert into AirportCode VALUES(null,'路易斯维尔','SDF','KSDF','路易斯维尔机场','LOUISVILLE');
insert into AirportCode VALUES(null,'Shimkent','CIT','','什姆肯特机场','SHIMKEN');
insert into AirportCode VALUES(null,'博罗尼亚','BLQ','LIPE','博罗尼亚机场','BOLOGNA');
insert into AirportCode VALUES(null,'浦那','PNQ','VAPO','浦那机场','PUNE');
insert into AirportCode VALUES(null,'韩国襄阳','YNY','RKNY','韩国襄阳机场','YANGYANG');
insert into AirportCode VALUES(null,'维萨卡帕特南','VTZ','','维萨卡帕特南机场','VISHAKHAPATNAM');
insert into AirportCode VALUES(null,'博兹曼','BZN','KBZN','博兹曼贝尔格莱德机场','BOZEMAN');
insert into AirportCode VALUES(null,'吉隆坡','SZB','WMSA','吉隆坡苏丹阿卜杜尔机场','KUALA LUMPUR');
insert into AirportCode VALUES(null,'拉默齐亚','SUF','LICA','拉默齐亚机场','LAMEZIA TERME');
insert into AirportCode VALUES(null,'哥达巴鲁','KBR','','哥达巴鲁机场','KOTA BHARU');
insert into AirportCode VALUES(null,'斋浦尔','JAI','VIJP','斋浦尔机场','JAIPUR');
insert into AirportCode VALUES(null,'瓦拉纳西','VNS','VIBN','瓦拉纳西机场','VARANASI');
insert into AirportCode VALUES(null,'皮乌拉','PIU','SPUR','皮乌拉机场','PIURA');
insert into AirportCode VALUES(null,'圣托里尼','JTR','','圣托里尼机场','SANTORINI');
insert into AirportCode VALUES(null,'杜马格特','DGT','RPVD','杜马格特机场','DUMAGUETE');
insert into AirportCode VALUES(null,'雷克亚未克','RKV','BIRK','雷克亚未克机场','REYKJAVIK');
insert into AirportCode VALUES(null,'加格达奇','JGD','','加格达奇机场','加格达奇');
insert into AirportCode VALUES(null,'苏福尔斯','FSD','KFSD','苏福尔斯机场','SIOUX FALLS');
insert into AirportCode VALUES(null,'布莱克布斯','BBS','','布莱克布斯机场','BLACKBUSH');
insert into AirportCode VALUES(null,'法戈','FAR','KFAR','法戈赫克机场','FARGO');
insert into AirportCode VALUES(null,'鄂木斯克','OMS','UNOO','鄂木斯克机场','OMSK');
insert into AirportCode VALUES(null,'尤金','EUG','KEUG','尤金机场','EUGENE');
insert into AirportCode VALUES(null,'罗阿诺克','ROA','KROA','罗阿诺克机场','罗阿诺克');
insert into AirportCode VALUES(null,'坦帕','TPA','','坦帕机场','TAMPA');
insert into AirportCode VALUES(null,'罗利达勒姆','RDU','KRDU','罗利达勒姆机场','RALEIGH DURHAM');
insert into AirportCode VALUES(null,'圣保罗','CGH','SBSP','圣保罗孔戈尼亚斯机场','SAO PAULO');
insert into AirportCode VALUES(null,'哥伦布','CSG','KCSG','哥伦布机场','COLUMBUS');
insert into AirportCode VALUES(null,'萨克拉门托','SMF','KSMF','萨克拉门托机场','SACRAMENTO');
insert into AirportCode VALUES(null,'弗卢里亚诺波利斯','FLN','','弗卢里亚诺波利斯机场','FLORIANOPOLIS');
insert into AirportCode VALUES(null,'塔林','TLL','EETN','伦纳特?梅里塔林机场','TALLINN');
insert into AirportCode VALUES(null,'阿达纳','ADA','LTAF','阿达纳机场','ADANA');
insert into AirportCode VALUES(null,'基韦斯德','EYW','','基韦斯德机场','KEY WEST');
insert into AirportCode VALUES(null,'埃阿坎','ECN','LCEN','埃阿坎机场','ERCAN');
insert into AirportCode VALUES(null,'圣塞瓦斯蒂安','EAS','','圣塞瓦斯蒂安机场','SAN SEBASTIAN');
insert into AirportCode VALUES(null,'卡尔斯巴德','CNM','','卡尔斯巴德机场','CARLSBAD');
insert into AirportCode VALUES(null,'布宜诺斯艾利斯','AEP','SABE','布宜诺斯艾利斯霍尔赫纽贝里机场','BUENOS AIRES');
insert into AirportCode VALUES(null,'阿斯彭','ASE','KASE','阿斯彭机场','ASPEN');
insert into AirportCode VALUES(null,'开塞利','ASR','LTAU','开塞利机场','KAYSERI');
insert into AirportCode VALUES(null,'希洛','ITO','PHTO','希洛机场','HILO');
insert into AirportCode VALUES(null,'希洛','ITO','PHTO','希洛机场','HILO');
insert into AirportCode VALUES(null,'科珀斯克里斯蒂','CRP','','科珀斯克里斯蒂机场','CORPUS CHRISTI');
insert into AirportCode VALUES(null,'佳特土','KDM','','佳特土机场','KAADEDHDHOO');
insert into AirportCode VALUES(null,'拉皮德城','RAP','','拉皮德城机场','RAPID CITY');
insert into AirportCode VALUES(null,'蒙特雷','MRY','','蒙特雷机场','MONTEREY');
insert into AirportCode VALUES(null,'亨德森','HNZ','','亨德森机场','HENDERSON');
insert into AirportCode VALUES(null,'顺化','HUI','VVPB','顺化富牌机场','HUE');
insert into AirportCode VALUES(null,'埃尔?帕索','ELP','','埃尔?帕索机场','EL PASO');
insert into AirportCode VALUES(null,'博卡拉','PKR','VNPK','博卡拉机场','POKHARA');
insert into AirportCode VALUES(null,'扎金索斯','ZTH','LGZA','扎金索斯机场','ZAKINTHOS');
insert into AirportCode VALUES(null,'盖恩斯维尔','GNV','KGNV','盖恩斯维尔机场','GAINESVILLE');
insert into AirportCode VALUES(null,'克雷塔罗','QRO','XXXX','克雷塔罗机场','QUERETARO');
insert into AirportCode VALUES(null,'海旁','LOP','WADL','海旁机场','PRAYA');
insert into AirportCode VALUES(null,'拉奈','LNY','PHNY','拉奈机场','LANAI CITY');
insert into AirportCode VALUES(null,'塔韦乌尼岛','TVU','','塔韦乌尼岛机场','TAVEUNI ISLAND');
insert into AirportCode VALUES(null,'格连吉克','GDZ','','格连吉克机场','GELENDZIK');
insert into AirportCode VALUES(null,'坎昆','CUN','MMUN','坎昆机场','CANCUN');
insert into AirportCode VALUES(null,'路易斯?穆尼奥斯?马林','SJU','TJSJ','路易斯?穆尼奥斯?马林机场','SAN JUAN');
insert into AirportCode VALUES(null,'贝洛奥里藏特','PLU','SBBH','贝洛奥里藏特机场','BELO HORIZONT');
insert into AirportCode VALUES(null,'贝洛奥里藏特','CNF','SBCF','坦克雷多内维斯机场','BELO HORIZONT');
insert into AirportCode VALUES(null,'瓦拉德','VRA','','瓦拉德机场','VARADERO');
insert into AirportCode VALUES(null,'乌贝兰迪亚','UDI','SBUL','乌贝兰迪亚机场','UBERLANDIA');
insert into AirportCode VALUES(null,'圣保罗','VCP','','坎皮纳斯机场','SAO PAULO');
insert into AirportCode VALUES(null,'阿拉卡茹','AJU','SBAR','阿拉卡茹机场','ARACAJU');
insert into AirportCode VALUES(null,'梅肯','MCN','KMCN','梅肯机场','MACON');
insert into AirportCode VALUES(null,'朱巴','JUB','HSSJ','朱巴机场','JUBA');
insert into AirportCode VALUES(null,'汕头','','ZGOW','揭阳机场','JIEYANG');
insert into AirportCode VALUES(null,'复活节岛','IPC','SCI','复活节岛马塔维里机场','EASTER ISLAND');
insert into AirportCode VALUES(null,'鸟取','YGJ','RJOH','鸟取机场','YONAGO');
insert into AirportCode VALUES(null,'帕皮提','PPT','NTAA','帕皮提机场','PAPEETE');
insert into AirportCode VALUES(null,'芽庄','CXR','','芽庄金兰机场','NHA TRANG');
insert into AirportCode VALUES(null,'埃因霍温','EIN','','埃因霍温机场','EINDHOVEN');
insert into AirportCode VALUES(null,'雪城','SYR','KSYR','雪城汉考克机场','SYRACUSE');
insert into AirportCode VALUES(null,'大叻','DLI','VVDL','大叻莲姜机场','DALAT');
insert into AirportCode VALUES(null,'美里','MYY','WBGR','美里机场','MIRI');
insert into AirportCode VALUES(null,'里贾纳','YQR','CYQR','里贾纳机场','REGINA');
insert into AirportCode VALUES(null,'阿比让','ABJ','DIAP','阿比让机场','ABIDJAN');
insert into AirportCode VALUES(null,'伊瓜苏瀑布','IGU','SBFI','伊瓜苏瀑布机场','IGUAZU FALLS');
insert into AirportCode VALUES(null,'龙讷比','RNB','','龙讷比机场','RONNEBY');
insert into AirportCode VALUES(null,'亚罗士打','AOR','WMKA','AOR机场','ALOR SETAR');
insert into AirportCode VALUES(null,'乌戎潘当','UPG','WAAA','乌戎潘当机场','UJUNG PANDANG');
insert into AirportCode VALUES(null,'荣市','VII','','荣市机场','VINH CITY');
insert into AirportCode VALUES(null,'克拉斯诺达','KRR','URKK','克拉斯诺达机场','KRASNODAR');
insert into AirportCode VALUES(null,'乞力马扎罗','JRO','HTKJ','乞力马扎罗机场','KILIMANJARO');
insert into AirportCode VALUES(null,'彭萨科拉','PNS','KPNS','彭萨科拉机场','PENSACOLA');
insert into AirportCode VALUES(null,'昌迪加尔','IXC','','昌迪加尔机场','CHANDIGARH');
insert into AirportCode VALUES(null,'日惹','JOG','WARJ','日惹机场','YOGYAKARTA');
insert into AirportCode VALUES(null,'卢武克','LUW','WAMW','卢武克机场','LUWUK');
insert into AirportCode VALUES(null,'伊拉克利翁','HER','','伊拉克利翁机场','HERAKLION');
insert into AirportCode VALUES(null,'山打根','SDK','WBKS','山打根机场','SANDAKAN');
insert into AirportCode VALUES(null,'布加斯','BOJ','','布加斯机场','BOURGAS');
insert into AirportCode VALUES(null,'阿特劳','GUW','UATG','阿特劳机场','ATYRAU');
insert into AirportCode VALUES(null,'利文斯通','LVI','FLLI','利文斯通机场','LIVINGSTONE');
insert into AirportCode VALUES(null,'蒙巴萨','MBA','HKMO','蒙巴萨机场','MOMBASA');
insert into AirportCode VALUES(null,'的里雅斯特','TRS','LIPQ','的里雅斯特机场','TRIESTE');
insert into AirportCode VALUES(null,'普拉森西亚','PLJ','','普拉森西亚机场','PLACENCIA');
insert into AirportCode VALUES(null,'彭世洛','PHS','VTPP','彭世洛机场','PHITSANULOK');
insert into AirportCode VALUES(null,'艾尔斯岩','AYQ','','康内尔兰机场','AYERS ROCK');
insert into AirportCode VALUES(null,'艾因','AAN','OMAL','艾因机场','AL AIN');
insert into AirportCode VALUES(null,'斯塔特大学','SCE','KUNV','斯塔特大学机场','STATE COLLEGE');
insert into AirportCode VALUES(null,'科罗尔','ROR','PTRO','科罗尔机场','KOROR');
insert into AirportCode VALUES(null,'莫罗尼','HAH','FMCH','莫罗尼机场','MORONI');
insert into AirportCode VALUES(null,'高知','KCZ','RJOK','高知机场','KOCHI');
insert into AirportCode VALUES(null,'诗巫','SBW','WBGS','诗巫机场','SIBU');
insert into AirportCode VALUES(null,'塞萨洛尼基','SKG','LGTS','塞萨洛尼基机场','THESSALONIKI');
insert into AirportCode VALUES(null,'万隆','BDO','WICC','万隆机场','BANDUNG');
insert into AirportCode VALUES(null,'富国岛','PQC','VVPQ','富国岛机场','PHU QUOC');
insert into AirportCode VALUES(null,'罗切斯特','ROC','KROC','罗切斯特机场','ROCHESTE');
insert into AirportCode VALUES(null,'小石城','LIT','KLIT','小石城机场','LITTLE ROCK');
insert into AirportCode VALUES(null,'德岛','TKS','RJOS','德岛机场','TOKUSHIMA');
insert into AirportCode VALUES(null,'女满别','MMB','RJCM','女满别机场','MEMANBETSU');
insert into AirportCode VALUES(null,'西棕榈滩','PBI','KPBI','西棕榈滩机场','WEST PALM BEACH');
insert into AirportCode VALUES(null,'林雪平','LPI','','林雪平机场','LINKOEPING');
insert into AirportCode VALUES(null,'汤斯维尔','TSV','YBTL','汤斯维尔机场','TOWNSVILLE');
insert into AirportCode VALUES(null,'恩贾梅纳','NDJ','FTTJ','恩贾梅纳机场','NDJAMENA');
insert into AirportCode VALUES(null,'艾丽斯斯普林斯','ASP','','艾丽斯斯普林斯机场','ALICE SPRINGS');
insert into AirportCode VALUES(null,'昆岛','VCS','','昆岛机场','CON DAO');
insert into AirportCode VALUES(null,'密尔沃基','MKE','KMKE','密尔沃基诺若机场','MILWAUKEE');
insert into AirportCode VALUES(null,'塔那那利佛','TNR','FMMI','塔那那利佛机场','ANTANANARIV');
insert into AirportCode VALUES(null,'诺克斯维尔','TYS','KTYS','诺克斯维尔机场','KNOXVILLE');
insert into AirportCode VALUES(null,'大溪城','GRR','','大溪城机场','GRAND RAPIDS');
insert into AirportCode VALUES(null,'圣丹尼斯','RUN','','圣丹尼斯机场','SAINT DENIS REUNION');
insert into AirportCode VALUES(null,'布隆方丹','BFN','FABL','布隆方丹机场','BLOEMFONTEIN');
insert into AirportCode VALUES(null,'阿雷格里港','POA','SBPA','阿雷格里港机场','PORTO ALEGRE');
insert into AirportCode VALUES(null,'弗雷斯诺','FAT','KFAT','弗雷斯诺机场','FRESNO');
insert into AirportCode VALUES(null,'桑给巴尔','ZNZ','HTZA','桑给巴尔机场','ZANZIBA');
insert into AirportCode VALUES(null,'亚松森','ASU','SGAS','亚松森机场','ASUNCION');
insert into AirportCode VALUES(null,'汉考克','CMX','KCMX','汉考克机场','HANCOCK');
insert into AirportCode VALUES(null,'海防','HPH','VVCI','海防机场','HAIPHONG');
insert into AirportCode VALUES(null,'芽庄','NHA','VVNT','芽庄机场','NHA TRANG');
insert into AirportCode VALUES(null,'麦卡伦','MFE','KMFE','麦卡伦机场','MCALLEN');
insert into AirportCode VALUES(null,'格拉纳达','GRX','','格拉纳达机场','GRANADA');
insert into AirportCode VALUES(null,'阿克套','SCO','UATE','阿克套机场','AKTAU');
insert into AirportCode VALUES(null,'克莱蒙费朗','CFE','','克莱蒙费朗机场','CLERMONT-FERRAND');
insert into AirportCode VALUES(null,'哥伦布','CMH','KCMH','哥伦布港机场','COLUMBUS');
insert into AirportCode VALUES(null,'萨马拉','KUF','UWWW','萨马拉机场','SAMARA');
insert into AirportCode VALUES(null,'热浪岛','RDN','','热浪岛机场','REDANG ISLAND');
insert into AirportCode VALUES(null,'莱城','LAE','','莱城机场','LAE');
insert into AirportCode VALUES(null,'科比亚波','CPO','SCHA','科比亚波机场','COPIAPO');
insert into AirportCode VALUES(null,'萨尔瓦多','ESR','','萨尔瓦多机场','萨尔瓦多');
insert into AirportCode VALUES(null,'归仁','UIH','VVQN','归仁机场','QUI NHON');
insert into AirportCode VALUES(null,'顿涅茨克','DOK','UKCC','顿涅茨克机场','DONETSK');
insert into AirportCode VALUES(null,'什里夫波特','SHV','KSHV','什里夫波特机场','SHREVEPORT');
insert into AirportCode VALUES(null,'迪比克','DBQ','KDBQ','迪比克机场','DUBUQUE');
insert into AirportCode VALUES(null,'卡拉特哈','KTA','','卡拉特哈机场','KARRATHA');
insert into AirportCode VALUES(null,'丽水','RSU','RKJY','丽水机场','YEOSU');
insert into AirportCode VALUES(null,'巨港','PLM','WIPP','巨港机场','PALEMBANG');
insert into AirportCode VALUES(null,'贝加莫','BGY','LIME','贝加莫机场','BERGAMO');
insert into AirportCode VALUES(null,'瓦伦西亚','VLC','LEVC','瓦伦西亚机场','VALENCIA');
insert into AirportCode VALUES(null,'穆龙达瓦','MOQ','FMMV','穆龙达瓦机场','MORONDAVA');
insert into AirportCode VALUES(null,'梅里达','MID','MMMD','梅里达机场','MERIDA');
insert into AirportCode VALUES(null,'圣马丽亚','SMX','','圣马丽亚机场','SANTA MARIA');
insert into AirportCode VALUES(null,'安科纳','AOI','LIPY','安科纳机场','ANCONA');
insert into AirportCode VALUES(null,'下瓦尔托夫斯克','NJC','','下瓦尔托夫斯克机场','NIZHNEVARTOVSK');
insert into AirportCode VALUES(null,'棕榈泉','PSP','KPSP','Palm Springs机场','PALM SPRINGS');
insert into AirportCode VALUES(null,'雷德蒙德','RDM','KRDM','雷德蒙德机场','REDMOND');
insert into AirportCode VALUES(null,'伊萨卡','ITH','KITH','伊萨卡机场','ITHACA');
insert into AirportCode VALUES(null,'普罗瑟派恩','PPP','','普罗瑟派恩机场','PROSERPINE');
insert into AirportCode VALUES(null,'蒙特利尔','YUL','CYUL','蒙特利尔特鲁多机场','MONTREAL');